import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JOBS,HOUSE_LEVELS,LOTS,BUILDINGS,ITEMS,FORAGE_NODES,addItem,itemCount,canAffordUpgrade,projectedNeeds,jobPay,houseInteriorBounds,sanitizePlacement,sanitizeIslandSnapshot} from '../public/island-life-core.mjs';
import {IslandLifeRoom} from '../islandLifeRoom.mjs';

const html=await readFile(new URL('../public/island-life.html',import.meta.url),'utf8');
const js=await readFile(new URL('../public/island-life.js',import.meta.url),'utf8');
const artjs=await readFile(new URL('../public/shared-3d-art-kit.mjs',import.meta.url),'utf8');
const gameplayjs=await readFile(new URL('../public/shared-3d-gameplay.mjs',import.meta.url),'utf8');
const css=await readFile(new URL('../public/island-life.css',import.meta.url),'utf8');
const app=await readFile(new URL('../public/app.js',import.meta.url),'utf8');
const worker=await readFile(new URL('../worker.mjs',import.meta.url),'utf8');
const wrangler=await readFile(new URL('../wrangler.jsonc',import.meta.url),'utf8');
const roomSource=await readFile(new URL('../islandLifeRoom.mjs',import.meta.url),'utf8');

class FakeSql{constructor(){this.row=null}exec(query,...args){if(/^SELECT json/i.test(query))return{toArray:()=>this.row?[{json:this.row}]:[]};if(/^INSERT INTO island_room/i.test(query)){this.row=args[0];return{toArray:()=>[]}}return{toArray:()=>[]}}}
function makeIslandRoom(){const sql=new FakeSql(),ctx={storage:{sql},blockConcurrencyWhile(fn){return Promise.resolve().then(fn)},getWebSockets(){return[]},acceptWebSocket(){},waitUntil(){}};return{room:new IslandLifeRoom(ctx,{}),sql}}
async function req(room,path,{method='GET',roomId='FAMILYISLAND',token,body}={}){const u=new URL(`https://game.test/api/island/${path}`);u.searchParams.set('room',roomId);if(token)u.searchParams.set('token',token);return room.fetch(new Request(u,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined}))}
async function createResident(room,name='Kristen',avatar='kristen'){const r=await req(room,'create',{method:'POST',body:{name,avatar,islandName:'Black Family Island'}});assert.equal(r.ok,true);return r.json()}

test('Family Island Life has a full family-sized world economy rather than a single-house demo',()=>{assert.equal(LOTS.length,13);assert.ok(Object.keys(JOBS).length>=9);assert.ok(Object.keys(BUILDINGS).length>=10);assert.ok(FORAGE_NODES.length>=40);assert.ok(Object.values(ITEMS).filter(x=>x.type==='furniture').length>=20);assert.equal(HOUSE_LEVELS.at(-1).name,'Two-Storey Tropical Villa')});
test('needs decay gently and jobs pay more as a resident gains skill',()=>{const r={needs:{energy:100,hunger:100,fun:100,social:100},needsUpdatedAt:1000},n=projectedNeeds(r,61000);assert.ok(n.energy>99&&n.energy<100);assert.ok(n.hunger>99&&n.hunger<100);assert.ok(jobPay('carpenter',25)>jobPay('carpenter',0))});
test('house upgrades require money and gathered materials',()=>{const r={money:1000,inventory:{},home:{level:0}};assert.equal(canAffordUpgrade(r,1),false);addItem(r.inventory,'wood',10);addItem(r.inventory,'stone',4);assert.equal(canAffordUpgrade(r,1),true);r.money=100;assert.equal(canAffordUpgrade(r,1),false)});
test('furniture placement is clamped inside the upgraded house footprint',()=>{const b=houseInteriorBounds(2),p=sanitizePlacement({x:500,z:-500,yaw:1.3},2);assert.equal(p.x,b.maxX);assert.equal(p.z,b.minZ);assert.equal(p.yaw,1.3);assert.ok(b.width>HOUSE_LEVELS[0].width)});
test('network movement clamps teleport attempts and invalid animation state',()=>{const s=sanitizeIslandSnapshot({x:900,y:-50,z:-900,vx:99,vy:-99,pitch:9,anim:'teleport',zone:'home',homeOwnerId:'owner'});assert.equal(s.x,58);assert.equal(s.y,-2);assert.equal(s.z,-58);assert.equal(s.vx,12);assert.equal(s.vy,-25);assert.equal(s.anim,'idle');assert.equal(s.homeOwnerId,'owner')});
test('Island Life uses true WebGL third-person all-angle humans and quadruped dogs',()=>{assert.ok(html.includes('/island-life.js'));for(const token of ['new THREE.WebGLRenderer','new THREE.PerspectiveCamera','buildHumanRig','buildDogRig','updateCamera','resolveActorOverlap'])assert.ok(js.includes(token),token);assert.ok(js.includes("create3DArtKit"));assert.ok(js.includes('/shared-3d-gameplay.mjs'));for(const token of ['createThirdPersonCamera','cameraObstructionDistance','animateFamilyRig','movementIntent','createPerformanceGovernor'])assert.ok(gameplayjs.includes(token),token);assert.ok(artjs.includes("face.position.set(0,.94,-.204)"));assert.ok(artjs.includes('tailPivot')&&artjs.includes('const legs=[]'));assert.ok(artjs.includes('CanvasTexture')&&artjs.includes('buildDetailedTree'));assert.doesNotMatch(js,/software-3D renderer/i)});
test('client builds island districts, stores, home exteriors, enterable interiors and decoration controls',()=>{for(const token of ['buildIsland','buildStore','buildHouseExterior','buildInterior','enterHome','exitHome','buildResourceNode','updateDayNight','openBuildMode','placeBuild'])assert.ok(js.includes(token),token);for(const district of ['Meadow rows / field','VACANT HOME LOT','Forest to the west','rocky cove','marina southeast','residential coast'])assert.ok(js.toLowerCase().includes(district.toLowerCase()),district);for(const ui of ['Inventory','Jobs','My Home','Wardrobe','Crafting','Residents'])assert.ok(js.includes(ui),ui);assert.ok(css.includes('.il-joystick'))});
test('Lodge creates a dedicated persistent Island Life room',()=>{assert.ok(app.includes('async function createIslandRoom'));assert.ok(app.includes("fetch('/api/island/create'"));assert.ok(app.includes("if(key==='island')return createIslandRoom(false)"));assert.ok(worker.includes("url.pathname.startsWith('/api/island/')"));assert.ok(worker.includes('env.ISLAND_LIFE.getByName(roomId)'));assert.ok(wrangler.includes('"ISLAND_LIFE"'));assert.ok(wrangler.includes('"IslandLifeRoom"'))});
test('persistent room creates and joins separate residents with private money and inventory',async()=>{const{room,sql}=makeIslandRoom(),created=await createResident(room);let r=await req(room,'join',{method:'POST',body:{name:'John',avatar:'john'}});assert.equal(r.ok,true);const joined=await r.json(),a=room.stateFor(created.playerToken),b=room.stateFor(joined.playerToken);assert.equal(a.residents.length,2);assert.equal(a.viewer.name,'Kristen');assert.equal(b.viewer.name,'John');assert.equal(a.viewer.money,1200);assert.deepEqual(a.viewer.wardrobe,['island_shirt']);assert.ok(sql.row.includes('Black Family Island'))});
test('lots cannot be claimed remotely and two residents cannot own the same lot',async()=>{const{room}=makeIslandRoom(),created=await createResident(room),p=room.room.residents[0];p.live={x:0,y:0,z:0,zone:'island'};let r=await req(room,'action',{method:'POST',body:{playerToken:created.playerToken,action:'claimLot',lotId:'lot01'}});assert.equal(r.status,409);const lot=LOTS[0];p.live={x:lot.x,y:0,z:lot.z,zone:'island'};r=await req(room,'action',{method:'POST',body:{playerToken:created.playerToken,action:'claimLot',lotId:'lot01'}});assert.equal(r.ok,true);r=await req(room,'join',{method:'POST',body:{name:'John',avatar:'john'}});const j=await r.json(),jp=room.room.residents[1];jp.live={x:lot.x,y:0,z:lot.z,zone:'island'};r=await req(room,'action',{method:'POST',body:{playerToken:j.playerToken,action:'claimLot',lotId:'lot01'}});assert.equal(r.status,409)});
test('jobs, shopping and gathering are server-authorized by world position and tools',async()=>{const{room}=makeIslandRoom(),created=await createResident(room),p=room.room.residents[0];await req(room,'action',{method:'POST',body:{playerToken:created.playerToken,action:'setJob',job:'barista'}});p.live={x:50,y:0,z:50,zone:'island'};let r=await req(room,'action',{method:'POST',body:{playerToken:created.playerToken,action:'work'}});assert.equal(r.status,409);p.live={x:BUILDINGS.coffee.x,y:0,z:BUILDINGS.coffee.z,zone:'island'};r=await req(room,'action',{method:'POST',body:{playerToken:created.playerToken,action:'work'}});assert.equal(r.ok,true);p.live={x:BUILDINGS.market.x,y:0,z:BUILDINGS.market.z,zone:'island'};r=await req(room,'action',{method:'POST',body:{playerToken:created.playerToken,action:'buy',store:'market',itemId:'axe'}});assert.equal(r.ok,true);assert.equal(itemCount(p.inventory,'axe'),1);const tree=FORAGE_NODES.find(n=>n.tool==='axe');p.live={x:tree.x,y:0,z:tree.z,zone:'island'};r=await req(room,'action',{method:'POST',body:{playerToken:created.playerToken,action:'forage',nodeId:tree.id}});assert.equal(r.ok,true);const d=await r.json();assert.ok(itemCount(p.inventory,d.itemId)>=1)});
test('home upgrades and furniture persist while decorating is restricted to the owner',async()=>{const{room}=makeIslandRoom(),created=await createResident(room),p=room.room.residents[0],lot=LOTS[1];p.live={x:lot.x,y:0,z:lot.z,zone:'island'};await req(room,'action',{method:'POST',body:{playerToken:created.playerToken,action:'claimLot',lotId:lot.id}});p.money=5000;p.inventory={wood:10,stone:4,sofa:1};let r=await req(room,'action',{method:'POST',body:{playerToken:created.playerToken,action:'upgradeHouse'}});assert.equal(r.ok,true);p.live={x:0,y:0,z:0,zone:'home',homeOwnerId:'other'};r=await req(room,'action',{method:'POST',body:{playerToken:created.playerToken,action:'placeFurniture',itemId:'sofa',x:0,z:0}});assert.equal(r.status,409);p.live={x:0,y:0,z:0,zone:'home',homeOwnerId:p.id};r=await req(room,'action',{method:'POST',body:{playerToken:created.playerToken,action:'placeFurniture',itemId:'sofa',x:999,z:999,yaw:.4}});assert.equal(r.ok,true);const placed=await r.json(),b=houseInteriorBounds(1);assert.equal(p.home.furniture.length,1);assert.equal(itemCount(p.inventory,'sofa'),0);assert.ok(placed.piece.x<=b.maxX&&placed.piece.z<=b.maxZ);assert.equal(room.stateFor(created.playerToken).viewer.home.furniture.length,1)});
test('Island Life Durable Object uses SQLite and hibernatable WebSockets',()=>{for(const token of ['ctx.storage.sql.exec','acceptWebSocket','serializeAttachment','deserializeAttachment','getWebSockets','webSocketMessage','webSocketClose'])assert.ok(roomSource.includes(token),token);assert.ok(wrangler.includes('new_sqlite_classes'));assert.ok(wrangler.includes('IslandLifeRoom'))});
