import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(new URL('..',import.meta.url).pathname),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const runtime='GAME-NIGHT-STAGING-PHASE-W29-FAMILY-V1-CANDIDATES-53',design='GAME-NIGHT-DESIGN-PHASE-W29-FAMILY-V1-CANDIDATES-53',version='3.26.0-staging-phase-w29-family-v1-candidates-53';
const candidates={kristen:'CHAR_KRISTEN.glb',holly:'CHAR_HOLLY.glb',vanessa:'CHAR_VANESSA.glb',elizabeth:'CHAR_LIZZIE.glb',logan:'CHAR_LOGAN.glb',james:'CHAR_JAMES.glb',dorothy:'CHAR_DOROTHY.glb'};
function glbJson(rel){const b=fs.readFileSync(path.join(root,rel));assert.equal(b.subarray(0,4).toString(),'glTF');let off=12;while(off<b.length){const len=b.readUInt32LE(off),type=b.subarray(off+4,off+8).toString();off+=8;const c=b.subarray(off,off+len);off+=len;if(type==='JSON')return JSON.parse(c.toString().replace(/\0+$/,'').trim())}throw Error('No JSON')}
test('W29 release identity and family lab are current',()=>{assert.equal(read('CURRENT_RELEASE.txt').trim(),runtime);assert.equal(read('DESIGN_RELEASE.txt').trim(),design);assert.equal(JSON.parse(read('package.json')).version,version);const app=read('public/app.js'),sw=read('public/sw.js'),qa=read('public/phase-e-qa.mjs'),shop=read('public/tokens-store.html');assert.match(app,new RegExp(`PHASE_W29_RELEASE='${runtime}'`));assert.match(app,/CURRENT_BUILD=PHASE_W29_RELEASE/);assert.match(app,/sw\.js\?v=W29-FAMILY-V1-CANDIDATES-53/);assert.match(sw,/PHASE_W29_CACHE='black-family-game-night-staging-phase-w29-family-v1-candidates-53'/);assert.match(sw,/const CACHE=PHASE_W29_CACHE/);assert.match(sw,/w29-family-v1-lab\.html/);assert.match(qa,new RegExp(`STAGING_BUILD_ID='${runtime}'`));assert.match(shop,/Family V1 Lab/)});
test('seven additional approved-turnaround humans have real skinned V1 candidate GLBs',()=>{for(const [id,file] of Object.entries(candidates)){const rel=`public/models/characters/approved/${file}`;assert.ok(fs.existsSync(path.join(root,rel)),id);assert.ok(fs.statSync(path.join(root,rel)).size>250000,id);const g=glbJson(rel),names=(g.nodes||[]).map(n=>n.name);assert.ok(names.includes('head'),id);assert.ok(names.includes('headSocket'),id);assert.ok(names.includes('approvedFacePatch'),id);assert.ok((g.skins||[]).length>=1,id);assert.ok((g.animations||[]).length>=19,id);assert.equal(g.asset?.extras?.characterId,id);assert.equal(g.asset?.extras?.familyV1Candidate,true);assert.match(g.asset?.extras?.sourceReference||'',new RegExp(`${id}-approved-turnaround\\.png$`))}});
test('W29 models remain candidates rather than falsely becoming final approved art',()=>{const reg=read('public/approved-family-characters.mjs'),lab=read('public/w29-family-v1-lab.html'),rt=read('public/w29-family-v1-runtime.mjs');for(const [id,file] of Object.entries(candidates)){assert.match(reg,new RegExp(`v1CandidateModel:'/models/characters/approved/${file.replace('.','\\.')}'`));assert.match(rt,new RegExp(file.replace('.','\\.')))}assert.match(lab,/candidate models/i);assert.match(lab,/not final art/i);assert.match(lab,/profile \/ hair refinement intentionally deferred/i)});
test('John Build 52 remains the V1 baseline and is not overwritten by W29 batch authoring',()=>{const g=glbJson('public/models/characters/john-production-skinned.glb');assert.equal(g.asset?.extras?.headRepair,'W27-JOHN-HEAD-REPAIR');assert.match(read('public/w29-family-v1-runtime.mjs'),/BUILD 52 V1 BASELINE/)});
