import {
  FAMILY_ID_SET,JOBS,HOUSE_LEVELS,LOTS,LOT_BY_ID,BUILDINGS,ITEMS,RECIPES,NODE_BY_ID,
  addItem,removeItem,itemCount,consumeItems,canAffordUpgrade,projectedNeeds,commitNeeds,boostNeeds,
  jobPay,sanitizePlacement,sanitizeIslandSnapshot,dist
} from './public/island-life-core.mjs';

const MAX_RESIDENTS=13;
const safeName=v=>String(v||'Resident').trim().slice(0,24)||'Resident';
const safeAvatar=v=>FAMILY_ID_SET.has(String(v||'').toLowerCase())?String(v).toLowerCase():'john';
const safeIslandName=v=>String(v||'Black Family Island').replace(/[<>]/g,'').trim().slice(0,32)||'Black Family Island';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
const token=()=>crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','').slice(0,8);
const residentByToken=(room,t)=>room?.residents?.find(p=>p.token===t)||null;
const hostOk=(room,t)=>!!t&&room?.hostToken===t;
const now=()=>Date.now();
const randomUint=()=>crypto.getRandomValues(new Uint32Array(1))[0]>>>0;
const validFloor=new Set(['pine','darkwood','sandstone','white-tile','slate']);
const validWall=new Set(['cream','sage','ocean','sunset','white','charcoal']);
const validExterior=new Set(['tropical','cabin','modern','beach']);

function newResident({name,avatar,seat=0}){const t=now();return{id:crypto.randomUUID(),token:token(),name:safeName(name),avatar:safeAvatar(avatar),seat,connected:true,money:1200,job:null,skills:{},workReadyAt:0,activityReadyAt:0,inventory:{},wardrobe:['island_shirt'],equippedClothing:null,needs:{energy:100,hunger:100,fun:100,social:100},needsUpdatedAt:t,home:null,live:null,joinedAt:t,lastActiveAt:t}}
function stableResident(p){return{id:p.id,token:p.token,name:p.name,avatar:p.avatar,seat:p.seat,money:p.money,job:p.job,skills:p.skills||{},workReadyAt:p.workReadyAt||0,activityReadyAt:p.activityReadyAt||0,inventory:p.inventory||{},wardrobe:p.wardrobe||[],equippedClothing:p.equippedClothing||null,needs:p.needs||{energy:100,hunger:100,fun:100,social:100},needsUpdatedAt:p.needsUpdatedAt||now(),home:p.home||null,joinedAt:p.joinedAt||now(),lastActiveAt:p.lastActiveAt||now()}}
function publicResident(p){return{id:p.id,name:p.name,avatar:p.avatar,seat:p.seat,connected:!!p.connected,job:p.job||null,equippedClothing:p.equippedClothing||null,home:p.home?{lotId:p.home.lotId,level:p.home.level||0,style:p.home.style||{floor:'pine',wall:'cream',exterior:'tropical'},furniture:p.home.furniture||[]}:null,live:p.live||null}}
function privateViewer(p){return p?{...publicResident(p),money:p.money||0,skills:p.skills||{},workReadyAt:p.workReadyAt||0,activityReadyAt:p.activityReadyAt||0,inventory:p.inventory||{},wardrobe:p.wardrobe||[],needs:projectedNeeds(p),needsUpdatedAt:now()}:null}
function safeQty(v,max=10){return Math.max(1,Math.min(max,Math.floor(Number(v)||1)))}
function nodeYield(kind){if(['hardwood','coral','fish'].includes(kind))return 1;if(['wood','stone','clay'].includes(kind))return 1+Math.floor(Math.random()*2);return 1+Math.floor(Math.random()*3)}
function publicNodeCooldowns(room){const out={},t=now();for(const [id,readyAt] of Object.entries(room.nodeCooldowns||{}))if(readyAt>t)out[id]=readyAt;return out}

export class IslandLifeRoom{
  constructor(ctx,env){this.ctx=ctx;this.env=env;this.room=null;this.ready=ctx.blockConcurrencyWhile(async()=>{ctx.storage.sql.exec('CREATE TABLE IF NOT EXISTS island_room (id INTEGER PRIMARY KEY CHECK(id=1), json TEXT NOT NULL, updated_at INTEGER NOT NULL)');const rows=ctx.storage.sql.exec('SELECT json FROM island_room WHERE id=1').toArray();if(rows.length){try{this.room=JSON.parse(rows[0].json);this.room.residents=(this.room.residents||[]).map(p=>({...p,connected:false,live:null}));this.room.nodeCooldowns=this.room.nodeCooldowns||{}}catch{this.room=null}}})}
  save(){if(!this.room)return;const stable={...this.room,residents:this.room.residents.map(stableResident)};this.ctx.storage.sql.exec('INSERT INTO island_room (id,json,updated_at) VALUES (1,?,?) ON CONFLICT(id) DO UPDATE SET json=excluded.json, updated_at=excluded.updated_at',JSON.stringify(stable),now())}
  bump(persist=true){if(!this.room)return;this.room.revision=(this.room.revision||0)+1;if(persist)this.save()}
  stateFor(tokenValue){if(!this.room)return null;const viewer=residentByToken(this.room,tokenValue),claimed=new Set(this.room.residents.map(r=>r.home?.lotId).filter(Boolean));return{id:this.room.id,islandName:this.room.islandName,createdAt:this.room.createdAt,revision:this.room.revision||0,residents:this.room.residents.map(publicResident),viewerId:viewer?.id||null,isHost:!!viewer&&viewer.id===this.room.hostPlayerId,hostPlayerId:this.room.hostPlayerId,viewer:privateViewer(viewer),lots:LOTS.map(l=>({...l,claimed:claimed.has(l.id),ownerId:this.room.residents.find(r=>r.home?.lotId===l.id)?.id||null})),nodeCooldowns:publicNodeCooldowns(this.room),dayAnchor:this.room.dayAnchor||this.room.createdAt,dayLengthMs:this.room.dayLengthMs||1200000,weatherSeed:this.room.weatherSeed||1,npcSeed:this.room.npcSeed||2}}
  broadcast(payload,except=null){const data=JSON.stringify(payload);for(const ws of this.ctx.getWebSockets()){if(ws===except)continue;try{if(ws.readyState===1)ws.send(data)}catch{}}}
  broadcastState(persist=true){this.bump(persist);for(const ws of this.ctx.getWebSockets()){const a=ws.deserializeAttachment?.()||{};try{if(ws.readyState===1)ws.send(JSON.stringify({type:'state',state:this.stateFor(a.token)}))}catch{}}}
  touch(p){if(!p)return;commitNeeds(p);p.lastActiveAt=now()}
  requireResident(body){return residentByToken(this.room,body.playerToken)}
  async fetch(request){await this.ready;const url=new URL(request.url),path=url.pathname;try{if(path==='/api/island/create'&&request.method==='POST')return this.create(request,url);if(path==='/api/island/join'&&request.method==='POST')return this.join(request);if(path==='/api/island/state'&&request.method==='GET'){const s=this.stateFor(url.searchParams.get('token'));return s?json(s):json({error:'Island not found'},404)}if(path==='/api/island/profile'&&request.method==='POST')return this.profile(request);if(path==='/api/island/action'&&request.method==='POST')return this.action(request);if(path==='/api/island/ws')return this.connectWebSocket(request,url);return json({error:'Unknown Island Life route'},404)}catch(err){console.error(JSON.stringify({message:'island life room error',path,error:err instanceof Error?err.message:String(err)}));return json({error:err instanceof Error?err.message:'Island Life server error'},500)}}
  async create(request,url){if(this.room)return json({error:'Island already exists'},409);const b=await request.json().catch(()=>({})),roomId=url.searchParams.get('room');if(!roomId)return json({error:'Missing island id'},400);const host=newResident({name:b.name||'Host',avatar:b.avatar||'john'});this.room={id:roomId,islandName:safeIslandName(b.islandName),createdAt:now(),dayAnchor:now(),dayLengthMs:1200000,revision:1,hostToken:token(),hostPlayerId:host.id,residents:[host],nodeCooldowns:{},weatherSeed:randomUint(),npcSeed:randomUint()};this.save();return json({roomId,hostToken:this.room.hostToken,playerToken:host.token,playerId:host.id})}
  async join(request){if(!this.room)return json({error:'Island not found'},404);if(this.room.residents.length>=MAX_RESIDENTS)return json({error:'This family island is full'},409);const b=await request.json().catch(()=>({})),p=newResident({name:b.name,avatar:b.avatar,seat:this.room.residents.length});this.room.residents.push(p);this.broadcastState(true);return json({roomId:this.room.id,playerToken:p.token,playerId:p.id})}
  async profile(request){if(!this.room)return json({error:'Island not found'},404);const b=await request.json().catch(()=>({})),p=this.requireResident(b);if(!p)return json({error:'Resident not found'},401);p.name=safeName(b.name||p.name);p.avatar=safeAvatar(b.avatar||p.avatar);this.touch(p);this.broadcastState(true);return json({ok:true})}
  near(p,place,extra=3){return !!p.live&&p.live.zone==='island'&&dist(p.live,place)<=Number(place.radius||0)+extra}
  async action(request){if(!this.room)return json({error:'Island not found'},404);const b=await request.json().catch(()=>({})),p=this.requireResident(b);if(!p)return json({error:'Resident not found'},401);const action=String(b.action||'');this.touch(p);
    if(action==='claimLot'){if(p.home)return json({error:'You already have a home lot'},409);const lot=LOT_BY_ID[String(b.lotId||'')];if(!lot)return json({error:'Unknown home lot'},400);if(!p.live||p.live.zone!=='island'||dist(p.live,lot)>4.2)return json({error:'Walk up to that home lot sign first'},409);if(this.room.residents.some(r=>r.home?.lotId===lot.id))return json({error:'That lot has already been claimed'},409);p.home={lotId:lot.id,level:0,style:{floor:'pine',wall:'cream',exterior:'tropical'},furniture:[]};boostNeeds(p,{fun:10});this.broadcastState(true);return json({ok:true,message:`${lot.label} is yours.`})}
    if(action==='setJob'){const job=String(b.job||'');if(job&&!JOBS[job])return json({error:'Unknown job'},400);p.job=job||null;p.workReadyAt=0;boostNeeds(p,{fun:3});this.broadcastState(true);return json({ok:true})}
    if(action==='work'){if(!p.job||!JOBS[p.job])return json({error:'Pick a job first'},409);const def=JOBS[p.job],place=BUILDINGS[def.building];if(p.workReadyAt>now())return json({error:'Your next shift is not ready yet'},429);if(!this.near(p,place,3))return json({error:`Go to ${place.name} to work this shift`},409);const xp=Number(p.skills?.[def.skill]||0),pay=jobPay(p.job,xp);p.money+=pay;p.skills[def.skill]=xp+1;p.workReadyAt=now()+def.cooldownMs;boostNeeds(p,{energy:-7,hunger:-6,fun:2,social:4});this.broadcastState(true);return json({ok:true,pay,xp:p.skills[def.skill]})}
    if(action==='buy'){const itemId=String(b.itemId||''),item=ITEMS[itemId],qty=safeQty(b.qty,['furniture','clothing','tool'].includes(item?.type)?1:10),store=String(b.store||'');if(!item||!item.buy||item.store!==store)return json({error:'That item is not sold here'},400);const shop=BUILDINGS[store];if(!shop||!this.near(p,shop,3))return json({error:`Go to ${shop?.name||'that shop'} to buy this`},409);const cost=item.buy*qty;if(p.money<cost)return json({error:'Not enough island money'},409);if(item.type==='clothing'&&p.wardrobe.includes(itemId))return json({error:'You already own that outfit'},409);p.money-=cost;if(item.type==='clothing')p.wardrobe.push(itemId);else addItem(p.inventory,itemId,qty);boostNeeds(p,{fun:['furniture','clothing'].includes(item.type)?3:0});this.broadcastState(true);return json({ok:true,cost})}
    if(action==='sell'){const itemId=String(b.itemId||''),item=ITEMS[itemId],qty=safeQty(b.qty,20);if(!item||!item.sell)return json({error:'That item cannot be sold'},400);if(!this.near(p,BUILDINGS.market,3))return json({error:'Go to Sunbasket Market to sell items'},409);if(item.type==='clothing')return json({error:'Clothing stays in your wardrobe'},409);if(itemCount(p.inventory,itemId)<qty)return json({error:'You do not have enough to sell'},409);removeItem(p.inventory,itemId,qty);const earned=item.sell*qty;p.money+=earned;this.broadcastState(true);return json({ok:true,earned})}
    if(action==='forage'){const node=NODE_BY_ID[String(b.nodeId||'')];if(!node)return json({error:'Resource not found'},404);const readyAt=Number(this.room.nodeCooldowns[node.id]||0);if(readyAt>now())return json({error:'That resource is growing back'},429);if(!p.live||p.live.zone!=='island'||dist(p.live,node)>3.6)return json({error:'Move closer to gather that'},409);if(node.tool&&itemCount(p.inventory,node.tool)<1)return json({error:`You need ${ITEMS[node.tool].name}`},409);const qty=nodeYield(node.kind);addItem(p.inventory,node.kind,qty);this.room.nodeCooldowns[node.id]=now()+node.cooldownMs;boostNeeds(p,{energy:-1,hunger:-.5,fun:2});this.broadcastState(true);return json({ok:true,itemId:node.kind,qty,readyAt:this.room.nodeCooldowns[node.id]})}
    if(action==='craft'){const recipe=RECIPES[String(b.recipeId||'')];if(!recipe)return json({error:'Unknown recipe'},400);if(!this.near(p,BUILDINGS.workshop,2.5))return json({error:'Visit the Island Workshop to craft'},409);if(!consumeItems(p.inventory,recipe.materials))return json({error:'You are missing crafting materials'},409);addItem(p.inventory,recipe.output,1);p.skills.crafting=Number(p.skills.crafting||0)+1;boostNeeds(p,{fun:2});this.broadcastState(true);return json({ok:true,itemId:recipe.output})}
    if(action==='upgradeHouse'){if(!p.home)return json({error:'Claim a home lot first'},409);const target=(p.home.level||0)+1,def=HOUSE_LEVELS[target];if(!def)return json({error:'Your home is already fully upgraded'},409);if(!canAffordUpgrade(p,target))return json({error:'You need more money or building materials'},409);p.money-=def.price;consumeItems(p.inventory,def.materials||{});p.home.level=target;boostNeeds(p,{fun:18,social:4});this.broadcastState(true);return json({ok:true,level:target,name:def.name})}
    if(action==='placeFurniture'){if(!p.home)return json({error:'Claim a home first'},409);if(!p.live||p.live.zone!=='home'||p.live.homeOwnerId!==p.id)return json({error:'Enter your own home to decorate'},409);const itemId=String(b.itemId||''),item=ITEMS[itemId];if(!item||item.type!=='furniture')return json({error:'Choose a furniture item'},400);if(itemCount(p.inventory,itemId)<1)return json({error:'That furniture is not in your inventory'},409);if((p.home.furniture||[]).length>=120)return json({error:'This home has reached the furniture limit'},409);const pos=sanitizePlacement(b,p.home.level||0),piece={id:crypto.randomUUID(),itemId,...pos};removeItem(p.inventory,itemId,1);p.home.furniture.push(piece);this.broadcastState(true);return json({ok:true,piece})}
    if(action==='moveFurniture'){if(!p.home||!p.live||p.live.zone!=='home'||p.live.homeOwnerId!==p.id)return json({error:'Enter your own home to move furniture'},409);const piece=p.home.furniture.find(x=>x.id===b.pieceId);if(!piece)return json({error:'Furniture not found'},404);Object.assign(piece,sanitizePlacement(b,p.home.level||0));this.broadcastState(true);return json({ok:true})}
    if(action==='removeFurniture'){if(!p.home||!p.live||p.live.zone!=='home'||p.live.homeOwnerId!==p.id)return json({error:'Enter your own home to pick up furniture'},409);const i=p.home.furniture.findIndex(x=>x.id===b.pieceId);if(i<0)return json({error:'Furniture not found'},404);const [piece]=p.home.furniture.splice(i,1);addItem(p.inventory,piece.itemId,1);this.broadcastState(true);return json({ok:true})}
    if(action==='useFurniture'){
      if(!p.live||p.live.zone!=='home'||!p.live.homeOwnerId)return json({error:'Enter a home first'},409);
      if((p.activityReadyAt||0)>now())return json({error:'Give that activity a moment'},429);
      const owner=this.room.residents.find(r=>r.id===p.live.homeOwnerId),piece=owner?.home?.furniture?.find(x=>x.id===String(b.pieceId||''));if(!piece)return json({error:'Furniture not found'},404);
      if(dist(p.live,piece)>3.1)return json({error:'Move closer to use that'},409);
      const kind=ITEMS[piece.itemId]?.kind||'',use=String(b.use||'');
      const allowed={chair:['sit'],sofa:['sit','relax'],hammock:['sit','relax'],tv:['watch'],tub:['bathe'],toilet:['use'],sink:['wash'],desk:['sit','work'],table:['sit'],counter:['use'],stove:['cook'],fridge:['use'],dresser:['wardrobe'],lamp:['light'],bed:['sit','sleep']};
      if(!(allowed[kind]||['use']).includes(use))return json({error:'That furniture cannot be used that way'},400);
      if(use==='sleep'&&owner.id!==p.id)return json({error:'You can only sleep in your own bed'},403);
      const boosts={sit:{energy:3,fun:2,social:1},relax:{energy:7,fun:6},watch:{fun:10,social:2},bathe:{energy:5,fun:5},use:{fun:1},wash:{energy:2,fun:1},work:{fun:1,energy:-2},cook:{hunger:4,fun:2},wardrobe:{fun:2},light:{fun:1},sleep:{energy:100,hunger:-4,fun:6,social:1}};
      boostNeeds(p,boosts[use]||boosts.use);if(use==='light')piece.on=piece.on===false?true:false;p.activityReadyAt=now()+(use==='sleep'?6500:3500);this.broadcastState(true);return json({ok:true,use,kind,on:piece.on,needs:p.needs});
    }
    if(action==='consume'){const itemId=String(b.itemId||''),item=ITEMS[itemId];if(!item?.needs)return json({error:'That item cannot be used this way'},400);if(!removeItem(p.inventory,itemId,1))return json({error:'You do not have that item'},409);boostNeeds(p,item.needs);this.broadcastState(true);return json({ok:true,needs:p.needs})}
    if(action==='sleep'){if(!p.home||!p.live||p.live.zone!=='home'||p.live.homeOwnerId!==p.id)return json({error:'Go home before sleeping'},409);boostNeeds(p,{energy:100,hunger:-4,fun:6,social:1});this.broadcastState(true);return json({ok:true})}
    if(action==='equipClothing'){const itemId=b.itemId?String(b.itemId):null;if(itemId&&(!ITEMS[itemId]||ITEMS[itemId].type!=='clothing'||!p.wardrobe.includes(itemId)))return json({error:'You do not own that outfit'},409);p.equippedClothing=itemId;boostNeeds(p,{fun:2});this.broadcastState(true);return json({ok:true})}
    if(action==='homeStyle'){if(!p.home)return json({error:'Claim a home first'},409);const floor=String(b.floor||p.home.style.floor),wall=String(b.wall||p.home.style.wall);if(!validFloor.has(floor)||!validWall.has(wall))return json({error:'Unknown home finish'},400);const changed=floor!==p.home.style.floor||wall!==p.home.style.wall;if(changed&&p.money<90)return json({error:'Home finishes cost $90'},409);if(changed)p.money-=90;p.home.style={...p.home.style,floor,wall,exterior:p.home.style?.exterior||'tropical'};this.broadcastState(true);return json({ok:true,cost:changed?90:0})}
    if(action==='houseExterior'){if(!p.home)return json({error:'Claim a home first'},409);const exterior=String(b.exterior||'tropical');if(!validExterior.has(exterior))return json({error:'Unknown house style'},400);const changed=exterior!==(p.home.style.exterior||'tropical');if(changed&&p.money<250)return json({error:'House exterior changes cost $250'},409);if(changed)p.money-=250;p.home.style.exterior=exterior;this.broadcastState(true);return json({ok:true,cost:changed?250:0})}
    if(action==='renameIsland'){if(!hostOk(this.room,b.hostToken))return json({error:'Host only'},403);this.room.islandName=safeIslandName(b.name);this.broadcastState(true);return json({ok:true})}
    if(action==='emote'){const emote=['wave','dance','cheer','sit'].includes(String(b.emote||''))?String(b.emote):'wave';boostNeeds(p,{fun:1,social:3});this.save();this.broadcast({type:'action',action:'emote',playerId:p.id,emote});return json({ok:true})}
    return json({error:'Unknown Island Life action'},400)
  }
  connectWebSocket(request,url){if(request.headers.get('Upgrade')!=='websocket')return new Response('Expected WebSocket',{status:426});if(!this.room)return new Response('Island not found',{status:404});const t=url.searchParams.get('token'),p=residentByToken(this.room,t);if(!p)return new Response('Resident not found',{status:401});const pair=new WebSocketPair(),[client,server]=Object.values(pair);this.ctx.acceptWebSocket(server,[`resident:${p.id}`]);server.serializeAttachment({playerId:p.id,token:t,isHost:p.id===this.room.hostPlayerId});p.connected=true;server.send(JSON.stringify({type:'state',state:this.stateFor(t)}));for(const q of this.room.residents)if(q.live)server.send(JSON.stringify({type:'snapshot',playerId:q.id,snapshot:q.live}));this.broadcast({type:'presence',playerId:p.id,connected:true},server);return new Response(null,{status:101,webSocket:client})}
  async webSocketMessage(ws,message){await this.ready;let msg;try{msg=JSON.parse(typeof message==='string'?message:new TextDecoder().decode(message))}catch{return}const auth=ws.deserializeAttachment?.()||{},p=this.room?.residents.find(r=>r.id===auth.playerId);if(!p)return;if(msg.type==='snapshot'){const snap=sanitizeIslandSnapshot(msg.snapshot||{},p.live||{});if(snap.zone==='home'&&!this.room.residents.some(r=>r.id===snap.homeOwnerId&&r.home))return;p.live=snap;p.connected=true;p.lastActiveAt=now();this.broadcast({type:'snapshot',playerId:p.id,snapshot:snap},ws);return}if(msg.type==='ping'){try{ws.send(JSON.stringify({type:'pong',at:now()}))}catch{}}}
  async webSocketClose(ws){await this.ready;const a=ws.deserializeAttachment?.()||{},p=this.room?.residents.find(q=>q.id===a.playerId);if(p){p.connected=false;this.broadcast({type:'presence',playerId:p.id,connected:false});this.broadcastState(false)}}
  async webSocketError(ws,error){console.error(JSON.stringify({message:'island life websocket error',error:String(error)}));try{ws.close(1011,'socket error')}catch{}}
}
