from pathlib import Path

ROOT=Path('/mnt/data/phase_u3_work')
PUB=ROOT/'public'

PROGRESS_JS=r'''
const BFGN_PROGRESS_KEY='bfgn_arcade_progress_v1';
const BFGN_ACH_KEY='bfgn_arcade_achievements_v1';
function bfRead(k,fallback){try{return JSON.parse(localStorage.getItem(k)||'')||fallback}catch{return fallback}}
function bfWrite(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function bfPlay(id){const p=bfRead(BFGN_PROGRESS_KEY,{plays:0,games:{},wins:0});p.plays=(p.plays||0)+1;p.games=p.games||{};p.games[id]=(p.games[id]||0)+1;bfWrite(BFGN_PROGRESS_KEY,p)}
function bfWin(){const p=bfRead(BFGN_PROGRESS_KEY,{plays:0,games:{},wins:0});p.wins=(p.wins||0)+1;bfWrite(BFGN_PROGRESS_KEY,p)}
function bfUnlock(id,label){const a=bfRead(BFGN_ACH_KEY,{});if(a[id])return false;a[id]={label,at:Date.now()};bfWrite(BFGN_ACH_KEY,a);const t=document.getElementById('toast');if(t){t.textContent='Achievement: '+label;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}return true}
'''

COMMON_CSS=r'''
:root{color-scheme:dark;--ink:#fff6e6;--muted:#baa98f;--gold:#e8b95c;--panel:#1b1510;--wood:#2a1b12;--accent:#d4934c}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:radial-gradient(circle at 50% 0,#46301f,#100c09 62%);font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:var(--ink)}body{display:grid;place-items:center;padding:10px}.wrap{width:min(100%,600px)}.head{display:flex;justify-content:space-between;align-items:end;gap:8px;margin:0 4px 8px}.brand{font-weight:950;letter-spacing:.07em;line-height:1.05}.brand small{display:block;font-size:10px;color:var(--gold);letter-spacing:.18em;margin-bottom:3px}.stats{font-size:11px;color:var(--muted);text-align:right}.stats b{color:var(--gold);font-size:18px}.foot{display:flex;justify-content:space-between;align-items:center;gap:9px;margin:7px 4px 0;font-size:11px;color:var(--muted);flex-wrap:wrap}a{color:var(--gold);text-decoration:none}.toast{position:absolute;left:50%;top:14px;transform:translate(-50%,-15px);opacity:0;background:#f4d793;color:#20130b;padding:10px 14px;border-radius:999px;font-weight:900;font-size:12px;pointer-events:none;transition:.2s;z-index:4;box-shadow:0 8px 28px #0008}.toast.show{opacity:1;transform:translate(-50%,0)}.stage{position:relative}button{font:inherit}
'''

def page(filename,title,character,brand,stats,canvas_attrs,controls,foot,script,extra_css=''):
    html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover,user-scalable=no"><title>{title} - Black Family Game Night</title><style>{COMMON_CSS}{extra_css}</style></head><body><div class="wrap"><div class="head"><div class="brand"><small>{character}</small>{brand}</div><div class="stats">{stats}</div></div><div class="stage"><div class="toast" id="toast"></div><canvas id="game" {canvas_attrs}></canvas></div>{controls}<div class="foot"><span>{foot}</span><a href="/">Back to Lodge</a></div></div><script>{PROGRESS_JS}{script}</script></body></html>'''
    (PUB/filename).write_text(html,encoding='utf-8')

# 1 Papa Paddle Battle
page('papas-paddle-battle.html',"Papa's Paddle Battle",'PAPA',"PAPA'S PADDLE BATTLE",
     'YOU <b id="you">0</b> / PAPA <b id="bot">0</b>',
     'width="720" height="960" aria-label="Papa paddle battle game"',
     '', 'Mouse / touch / arrows. First to 7.',r'''
(()=>{const c=document.getElementById('game'),g=c.getContext('2d'),W=c.width,H=c.height,youEl=document.getElementById('you'),botEl=document.getElementById('bot');let state='ready',you=0,bot=0,last=performance.now(),left=false,right=false,msg='Defend the shop. Blame Nana if you lose.';const p={x:W/2,w:165,y:H-72,h:24},ai={x:W/2,w:154,y:72,h:24};let ball={x:W/2,y:H/2,vx:230,vy:315,r:14,speed:390};
function resetBall(dir=Math.random()<.5?-1:1){ball={x:W/2,y:H/2,vx:(Math.random()*.8-.4)*260,vy:dir*330,r:14,speed:390}}
function start(){if(state==='over'){you=0;bot=0;youEl.textContent='0';botEl.textContent='0'}state='play';msg='';bfPlay('papas-paddle-battle');resetBall(Math.random()<.5?-1:1)}
function pointerX(e){const r=c.getBoundingClientRect();p.x=Math.max(p.w/2,Math.min(W-p.w/2,(e.clientX-r.left)*W/r.width))}
c.addEventListener('pointermove',e=>{if(e.buttons||e.pointerType!=='mouse')pointerX(e)});c.addEventListener('pointerdown',e=>{c.setPointerCapture?.(e.pointerId);pointerX(e);if(state!=='play')start()});addEventListener('keydown',e=>{if(['ArrowLeft','a','A'].includes(e.key))left=true;if(['ArrowRight','d','D'].includes(e.key))right=true;if(e.code==='Space'&&state!=='play'){e.preventDefault();start()}});addEventListener('keyup',e=>{if(['ArrowLeft','a','A'].includes(e.key))left=false;if(['ArrowRight','d','D'].includes(e.key))right=false});
function hit(pd,down){const top=pd.y-pd.h/2,bottom=pd.y+pd.h/2;if(down?ball.vy<=0:ball.vy>=0)return false;if(ball.x+ball.r<pd.x-pd.w/2||ball.x-ball.r>pd.x+pd.w/2||ball.y+ball.r<top||ball.y-ball.r>bottom)return false;const off=(ball.x-pd.x)/(pd.w/2),angle=off*1.08;ball.speed=Math.min(760,ball.speed+18);ball.vx=Math.sin(angle)*ball.speed;ball.vy=(down?-1:1)*Math.cos(angle)*ball.speed;ball.y=down?top-ball.r:bottom+ball.r;return true}
function point(who){if(who==='you'){you++;youEl.textContent=you}else{bot++;botEl.textContent=bot}if(you>=7||bot>=7){state='over';if(you>bot){msg='Papa Approved.';bfUnlock('papa-approved','Papa Approved');bfWin()}else msg='Papa is still got it. Nana probably distracted you.'}else{state='serve';setTimeout(()=>{if(state==='serve'){state='play';resetBall(who==='you'?1:-1)}},620)}}
function update(dt){if(state!=='play')return;if(left)p.x-=520*dt;if(right)p.x+=520*dt;p.x=Math.max(p.w/2,Math.min(W-p.w/2,p.x));const target=ball.x+ball.vx*.11,sp=360+Math.min(180,(you+bot)*18);ai.x+=Math.max(-sp*dt,Math.min(sp*dt,target-ai.x));ai.x=Math.max(ai.w/2,Math.min(W-ai.w/2,ai.x));let rem=dt;for(let i=0;i<6&&rem>0;i++){const st=Math.min(rem,.005);ball.x+=ball.vx*st;ball.y+=ball.vy*st;rem-=st;if(ball.x-ball.r<18&&ball.vx<0){ball.x=18+ball.r;ball.vx*=-1}if(ball.x+ball.r>W-18&&ball.vx>0){ball.x=W-18-ball.r;ball.vx*=-1}hit(p,true);hit(ai,false);if(ball.y<-42){point('you');break}if(ball.y>H+42){point('bot');break}}}
function chair(){g.fillStyle='#b59b48';g.beginPath();g.roundRect(56,370,80,105,22);g.fill();g.fillStyle='#8e7437';g.fillRect(68,450,10,55);g.fillRect(116,450,10,55);g.strokeStyle='#6e562c';g.lineWidth=6;g.strokeRect(56,370,80,105)}
function fireplace(){g.fillStyle='#4a2a1c';g.fillRect(W-154,352,102,132);g.fillStyle='#111';g.fillRect(W-134,396,62,68);g.fillStyle='#ff8e3f';g.beginPath();g.moveTo(W-104,450);g.quadraticCurveTo(W-130,420,W-103,406);g.quadraticCurveTo(W-75,430,W-104,450);g.fill()}
function draw(){const bg=g.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#382116');bg.addColorStop(.5,'#160f0b');bg.addColorStop(1,'#3a2114');g.fillStyle=bg;g.fillRect(0,0,W,H);for(let x=75;x<W;x+=95){g.strokeStyle='#7c553433';g.beginPath();g.moveTo(x,28);g.lineTo(x,H-28);g.stroke()}chair();fireplace();g.fillStyle='#8c6544';for(let i=0;i<5;i++)g.fillRect(180+i*75,132+(i%2)*18,42,8);g.strokeStyle='#8b5e39';g.lineWidth=10;g.strokeRect(18,18,W-36,H-36);g.setLineDash([14,18]);g.strokeStyle='#765337';g.lineWidth=3;g.beginPath();g.moveTo(30,H/2);g.lineTo(W-30,H/2);g.stroke();g.setLineDash([]);
function paddle(pd,player){const rg=g.createLinearGradient(pd.x-pd.w/2,0,pd.x+pd.w/2,0);rg.addColorStop(0,'#4a2c1b');rg.addColorStop(.5,player?'#d39a56':'#8e684a');rg.addColorStop(1,'#3a2418');g.fillStyle=rg;g.strokeStyle='#f0d29b';g.lineWidth=3;g.beginPath();g.roundRect(pd.x-pd.w/2,pd.y-pd.h/2,pd.w,pd.h,10);g.fill();g.stroke();g.fillStyle='#21140e';g.fillRect(pd.x-6,pd.y-pd.h/2-7,12,7)}paddle(ai,false);paddle(p,true);g.save();g.shadowColor='#ff8b3d';g.shadowBlur=28;g.fillStyle='#ffb34e';g.beginPath();g.arc(ball.x,ball.y,ball.r,0,Math.PI*2);g.fill();g.fillStyle='#fff3b0';g.beginPath();g.arc(ball.x-4,ball.y-4,4,0,Math.PI*2);g.fill();g.restore();if(state!=='play'&&state!=='serve'){g.fillStyle='#0d0806dc';g.fillRect(0,0,W,H);g.textAlign='center';g.fillStyle='#e8b95c';g.font='800 18px system-ui';g.fillText('PAPA',W/2,H*.34);g.fillStyle='#fff6df';g.font='950 50px system-ui';g.fillText(state==='over'?(you>bot?'PAPA APPROVED':'SHOP CLOSED'):"PAPA'S PADDLE BATTLE",W/2,H*.42);g.fillStyle='#e8b95c';g.font='700 21px system-ui';g.fillText(state==='over'?`${you} - ${bot}`:'Defend the shop. Blame Nana if you lose.',W/2,H*.49);g.fillStyle='#d0c1aa';g.font='17px system-ui';g.fillText(state==='over'?msg:'Tap / Space to serve',W/2,H*.55);if(state==='over')g.fillText('Tap to rematch',W/2,H*.60)}}
function loop(t){const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop)})();
''',extra_css='canvas{display:block;width:100%;aspect-ratio:3/4;background:#1b120d;border:2px solid #7c5534;border-radius:22px;box-shadow:0 18px 58px #0009;touch-action:none}')

# 2 Gunner Goat Run
page('gunners-goat-run.html',"Gunner's Goat Run",'GUNNER',"GUNNER'S GOAT RUN",
     'SAVED <b id="score">0</b> / LIVES <b id="lives">3</b> / LEVEL <b id="level">1</b>',
     'width="600" height="1000" aria-label="Gunner goat run crossing game"',
     '', 'Arrows / WASD / swipe. Get Gunner to the goat pen.',r'''
(()=>{const c=document.getElementById('game'),g=c.getContext('2d'),W=c.width,H=c.height,scoreEl=document.getElementById('score'),livesEl=document.getElementById('lives'),levelEl=document.getElementById('level');const laneH=100;let state='ready',saved=0,lives=3,level=1,last=performance.now(),inv=0,message='Help the big guy get the goats home.';const dog={x:300,y:930,r:28};let movers=[];const lanes=[{type:'goal',y:50},{type:'grass',y:150},{type:'water',y:250,dir:1,spd:78},{type:'water',y:350,dir:-1,spd:92},{type:'grass',y:450},{type:'road',y:550,dir:1,spd:120},{type:'road',y:650,dir:-1,spd:150},{type:'road',y:750,dir:1,spd:175},{type:'road',y:850,dir:-1,spd:112},{type:'start',y:950}];
function rebuild(){movers=[];for(const l of lanes){if(l.type==='road')for(let i=0;i<4;i++)movers.push({type:'vehicle',lane:l,x:i*190+Math.random()*40,y:l.y,w:90,h:48,dir:l.dir,spd:l.spd*(1+.12*(level-1)),kind:i%3});if(l.type==='water')for(let i=0;i<3;i++)movers.push({type:'log',lane:l,x:i*230+Math.random()*60,y:l.y,w:145,h:42,dir:l.dir,spd:l.spd*(1+.09*(level-1))})}}
function resetDog(){dog.x=300;dog.y=930;inv=.75}
function begin(){if(state==='over'){saved=0;lives=3;level=1;scoreEl.textContent=0;livesEl.textContent=3;levelEl.textContent=1}state='play';message='';bfPlay('gunners-goat-run');rebuild();resetDog()}
function move(dx,dy){if(state!=='play'){begin();return}dog.x=Math.max(30,Math.min(W-30,dog.x+dx*60));dog.y=Math.max(50,Math.min(950,dog.y+dy*100))}
addEventListener('keydown',e=>{const m={ArrowLeft:[-1,0],a:[-1,0],A:[-1,0],ArrowRight:[1,0],d:[1,0],D:[1,0],ArrowUp:[0,-1],w:[0,-1],W:[0,-1],ArrowDown:[0,1],s:[0,1],S:[0,1]}[e.key];if(m){e.preventDefault();move(...m)}if(e.code==='Space'&&state!=='play')begin()});let sx=0,sy=0;c.addEventListener('pointerdown',e=>{if(state!=='play'){begin();return}sx=e.clientX;sy=e.clientY;c.setPointerCapture?.(e.pointerId)});c.addEventListener('pointerup',e=>{if(state!=='play')return;const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)<18&&Math.abs(dy)<18){move(0,-1);return}Math.abs(dx)>Math.abs(dy)?move(Math.sign(dx),0):move(0,Math.sign(dy))});
function laneAt(y){return lanes.reduce((a,b)=>Math.abs(b.y-y)<Math.abs(a.y-y)?b:a,lanes[0])}function hit(o){return Math.abs(dog.x-o.x)<o.w/2+dog.r*.7&&Math.abs(dog.y-o.y)<o.h/2+dog.r*.7}
function lose(){if(inv>0)return;lives--;livesEl.textContent=lives;message=['Gunner forgot what he was doing.','Snack break.','Wrong way, big guy.'][Math.floor(Math.random()*3)];if(lives<=0)state='over';else resetDog()}
function update(dt){if(state!=='play')return;inv=Math.max(0,inv-dt);for(const o of movers){o.x+=o.spd*o.dir*dt;if(o.dir>0&&o.x-o.w/2>W+30)o.x=-o.w/2-30;if(o.dir<0&&o.x+o.w/2<-30)o.x=W+o.w/2+30}const lane=laneAt(dog.y);if(lane.type==='road'){for(const o of movers)if(o.lane===lane&&o.type==='vehicle'&&hit(o)){lose();break}}if(lane.type==='water'){let log=null;for(const o of movers)if(o.lane===lane&&o.type==='log'&&hit(o)){log=o;break}if(log){dog.x+=log.spd*log.dir*dt;if(dog.x<15||dog.x>W-15)lose()}else lose()}if(dog.y<=70&&state==='play'){saved++;scoreEl.textContent=saved;level++;levelEl.textContent=level;if(saved>=5)bfUnlock('good-boy-gunner','Good Boy Gunner');rebuild();resetDog()}}
function drawDog(){if(inv>0&&Math.floor(inv*12)%2)return;g.save();g.translate(dog.x,dog.y);g.fillStyle='#6a4c37';g.strokeStyle='#2b2119';g.lineWidth=4;g.beginPath();g.ellipse(0,8,34,23,0,0,Math.PI*2);g.fill();g.stroke();g.beginPath();g.arc(3,-20,24,0,Math.PI*2);g.fill();g.stroke();g.beginPath();g.moveTo(-10,-37);g.lineTo(-25,-55);g.lineTo(-19,-27);g.moveTo(15,-37);g.lineTo(27,-51);g.lineTo(24,-25);g.stroke();g.fillStyle='#18130f';g.beginPath();g.arc(-5,-23,3,0,Math.PI*2);g.arc(10,-23,3,0,Math.PI*2);g.fill();g.fillStyle='#e88b8b';g.fillRect(-2,-2,12,18);g.fillStyle='#d9c5a3';g.font='900 12px system-ui';g.textAlign='center';g.fillText('GUNNER',0,42);g.restore()}
function draw(){g.fillStyle='#254f2e';g.fillRect(0,0,W,H);for(const l of lanes){const top=l.y-laneH/2;if(l.type==='road'){g.fillStyle='#292c2b';g.fillRect(0,top,W,laneH);g.strokeStyle='#d9b35f';g.setLineDash([28,28]);g.beginPath();g.moveTo(0,l.y);g.lineTo(W,l.y);g.stroke();g.setLineDash([])}else if(l.type==='water'){g.fillStyle='#20516c';g.fillRect(0,top,W,laneH);for(let x=0;x<W;x+=80){g.strokeStyle='#ffffff24';g.beginPath();g.arc(x+20,l.y+12,25,Math.PI,Math.PI*2);g.stroke()}}else{g.fillStyle=l.type==='goal'?'#49753b':l.type==='start'?'#365a2f':'#3d6935';g.fillRect(0,top,W,laneH)}}g.fillStyle='#d7c275';for(let x=80;x<W;x+=140){g.beginPath();g.arc(x,52,18,0,Math.PI*2);g.fill();g.strokeStyle='#4e4032';g.beginPath();g.moveTo(x-10,40);g.lineTo(x-18,28);g.moveTo(x+10,40);g.lineTo(x+18,28);g.stroke()}for(const o of movers){if(o.type==='vehicle'){g.fillStyle=o.kind===0?'#777f83':o.kind===1?'#7e5436':'#5c744b';g.beginPath();g.roundRect(o.x-o.w/2,o.y-o.h/2,o.w,o.h,12);g.fill();g.fillStyle='#dce7e8';g.fillRect(o.x-22,o.y-o.h/2+7,44,11);g.fillStyle='#161616';g.beginPath();g.arc(o.x-o.w*.3,o.y+o.h/2,9,0,Math.PI*2);g.arc(o.x+o.w*.3,o.y+o.h/2,9,0,Math.PI*2);g.fill()}else{g.fillStyle='#6e4326';g.strokeStyle='#a6784f';g.lineWidth=3;g.beginPath();g.roundRect(o.x-o.w/2,o.y-o.h/2,o.w,o.h,20);g.fill();g.stroke()}}drawDog();if(state!=='play'){g.fillStyle='#0c1009dd';g.fillRect(0,0,W,H);g.textAlign='center';g.fillStyle='#e8b95c';g.font='800 18px system-ui';g.fillText('GUNNER',W/2,H*.33);g.fillStyle='#f6f3e7';g.font='950 49px system-ui';g.fillText(state==='over'?'GUNNER GOT DISTRACTED':"GUNNER'S GOAT RUN",W/2,H*.41);g.fillStyle='#e8b95c';g.font='700 21px system-ui';g.fillText(state==='over'?`Goats saved: ${saved}`:'Help the big guy get the goats home.',W/2,H*.48);g.fillStyle='#d0c7b5';g.font='17px system-ui';g.fillText(state==='over'?message:'Tap or press a direction to start',W/2,H*.54)}}
function loop(t){const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}rebuild();requestAnimationFrame(loop)})();
''',extra_css='canvas{display:block;width:100%;aspect-ratio:3/5;background:#17371f;border:1px solid #5d5131;border-radius:20px;box-shadow:0 18px 58px #0009;touch-action:none}')

# 3 John's Shop Bomber
page('johns-shop-bomber.html',"John's Shop Bomber",'JOHN',"JOHN'S SHOP BOMBER",
     'SCORE <b id="score">0</b> / LIVES <b id="lives">3</b> / ROOM <b id="room">1</b>',
     'width="650" height="750" aria-label="John shop blaster maze game"',
     '<div class="controls"><div class="dpad"><button class="up" data-d="0,-1">UP</button><button class="left" data-d="-1,0">LEFT</button><button class="down" data-d="0,1">DOWN</button><button class="right" data-d="1,0">RIGHT</button></div><span></span><button class="charge" id="charge">SPARK CHARGE</button></div>',
     'Arrows / WASD. Space places a safe spark charge.',r'''
(()=>{const c=document.getElementById('game'),g=c.getContext('2d'),COL=13,ROW=15,S=50,scoreEl=document.getElementById('score'),livesEl=document.getElementById('lives'),roomEl=document.getElementById('room');let state='ready',score=0,lives=3,room=1,last=performance.now(),grid=[],charges=[],blasts=[],enemies=[],enemyClock=0,inv=0,msg='John fixes the shop. The shop disagrees.';const player={x:1,y:13};const key=(x,y)=>y*COL+x;function solid(x,y){return x<0||y<0||x>=COL||y>=ROW||grid[key(x,y)]===1||grid[key(x,y)]===2||charges.some(b=>b.x===x&&b.y===y)}
function makeRoom(){grid=Array(COL*ROW).fill(0);for(let y=0;y<ROW;y++)for(let x=0;x<COL;x++){if(x===0||y===0||x===COL-1||y===ROW-1||(x%2===0&&y%2===0))grid[key(x,y)]=1;else if(Math.random()<.30)grid[key(x,y)]=2}for(const [x,y] of [[1,13],[1,12],[2,13],[11,1],[10,1],[11,2],[11,13],[10,13],[11,12],[1,1],[1,2],[2,1]])grid[key(x,y)]=0;player.x=1;player.y=13;charges=[];blasts=[];const spots=[[11,1],[11,13],[1,1],[7,1],[11,7]];enemies=spots.slice(0,Math.min(3+Math.floor((room-1)/2),5)).map((e,i)=>({x:e[0],y:e[1],kind:['tire','vac','toolbox'][i%3],dead:false}));inv=1}
function begin(){if(state==='over'){score=0;lives=3;room=1;scoreEl.textContent=0;livesEl.textContent=3;roomEl.textContent=1}state='play';msg='';bfPlay('johns-shop-bomber');makeRoom()}
function move(dx,dy){if(state!=='play'){begin();return}const nx=player.x+dx,ny=player.y+dy;if(!solid(nx,ny)){player.x=nx;player.y=ny}}
function place(){if(state!=='play'){begin();return}if(charges.length>=2||charges.some(b=>b.x===player.x&&b.y===player.y))return;charges.push({x:player.x,y:player.y,t:1.55})}
function explode(b){const cells=[[b.x,b.y]];for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]])for(let r=1;r<=2;r++){const x=b.x+dx*r,y=b.y+dy*r;if(x<0||y<0||x>=COL||y>=ROW||grid[key(x,y)]===1)break;cells.push([x,y]);if(grid[key(x,y)]===2){grid[key(x,y)]=0;score+=5;scoreEl.textContent=score;break}}for(const [x,y] of cells)blasts.push({x,y,t:.32});for(const e of enemies)if(!e.dead&&cells.some(q=>q[0]===e.x&&q[1]===e.y)){e.dead=true;score+=100;scoreEl.textContent=score}if(cells.some(q=>q[0]===player.x&&q[1]===player.y))hurt()}
function hurt(){if(inv>0)return;lives--;livesEl.textContent=lives;msg='John: I can fix that.';if(lives<=0)state='over';else{player.x=1;player.y=13;inv=1.2}}
function enemyMove(){const dirs=[[1,0],[-1,0],[0,1],[0,-1]];for(const e of enemies){if(e.dead)continue;const ranked=dirs.map(d=>({d,s:Math.abs(player.x-(e.x+d[0]))+Math.abs(player.y-(e.y+d[1]))+Math.random()*3})).sort((a,b)=>a.s-b.s);for(const q of ranked){const nx=e.x+q.d[0],ny=e.y+q.d[1];if(!solid(nx,ny)&&!enemies.some(o=>o!==e&&!o.dead&&o.x===nx&&o.y===ny)){e.x=nx;e.y=ny;break}}if(e.x===player.x&&e.y===player.y)hurt()}}
function update(dt){if(state!=='play')return;inv=Math.max(0,inv-dt);enemyClock+=dt;if(enemyClock>.42){enemyClock=0;enemyMove()}for(const b of charges)b.t-=dt;for(const b of charges.filter(x=>x.t<=0))explode(b);charges=charges.filter(x=>x.t>0);for(const b of blasts)b.t-=dt;blasts=blasts.filter(x=>x.t>0);for(const e of enemies)if(!e.dead&&blasts.some(b=>b.x===e.x&&b.y===e.y)){e.dead=true;score+=100;scoreEl.textContent=score}if(enemies.length&&enemies.every(e=>e.dead)){room++;roomEl.textContent=room;score+=250;scoreEl.textContent=score;if(room>=4)bfUnlock('john-fix-it','John Fix-It');makeRoom()}}
addEventListener('keydown',e=>{const d={ArrowLeft:[-1,0],a:[-1,0],A:[-1,0],ArrowRight:[1,0],d:[1,0],D:[1,0],ArrowUp:[0,-1],w:[0,-1],W:[0,-1],ArrowDown:[0,1],s:[0,1],S:[0,1]}[e.key];if(d){e.preventDefault();move(...d)}if(e.code==='Space'){e.preventDefault();place()}});document.querySelectorAll('[data-d]').forEach(b=>b.addEventListener('pointerdown',()=>move(...b.dataset.d.split(',').map(Number))));document.getElementById('charge').addEventListener('pointerdown',place);c.addEventListener('pointerdown',()=>{if(state!=='play')begin()});
function drawJohn(x,y){const px=x*S+S/2,py=y*S+S/2;g.save();g.translate(px,py);g.fillStyle='#caa06a';g.beginPath();g.arc(0,-7,12,0,Math.PI*2);g.fill();g.fillStyle='#7b3d32';g.fillRect(-14,5,28,22);g.strokeStyle='#e2c5a0';g.lineWidth=2;for(let q=-10;q<=10;q+=10){g.beginPath();g.moveTo(q,5);g.lineTo(q,27);g.stroke()}g.beginPath();g.moveTo(-14,13);g.lineTo(14,13);g.stroke();g.fillStyle='#34271f';g.fillRect(-12,27,9,13);g.fillRect(3,27,9,13);g.strokeStyle='#d9b15c';g.lineWidth=4;g.beginPath();g.moveTo(15,5);g.lineTo(26,-8);g.stroke();g.beginPath();g.arc(28,-10,5,0,Math.PI*2);g.stroke();g.restore()}
function drawEnemy(e){const px=e.x*S+S/2,py=e.y*S+S/2;g.save();g.translate(px,py);if(e.kind==='tire'){g.strokeStyle='#222';g.lineWidth=10;g.beginPath();g.arc(0,0,14,0,Math.PI*2);g.stroke();g.strokeStyle='#777';g.lineWidth=3;g.stroke()}else if(e.kind==='vac'){g.fillStyle='#5c6a70';g.beginPath();g.roundRect(-15,-18,30,36,8);g.fill();g.strokeStyle='#aaa';g.beginPath();g.moveTo(8,-15);g.quadraticCurveTo(24,-25,22,5);g.stroke()}else{g.fillStyle='#b34f3e';g.fillRect(-18,-13,36,27);g.fillStyle='#d8bd87';g.fillRect(-7,-20,14,7)}g.restore()}
function draw(){g.fillStyle='#23180f';g.fillRect(0,0,c.width,c.height);for(let y=0;y<ROW;y++)for(let x=0;x<COL;x++){const t=grid[key(x,y)],px=x*S,py=y*S;g.strokeStyle='#1a120c';g.strokeRect(px,py,S,S);if(t===1){g.fillStyle='#4b3728';g.fillRect(px+3,py+3,S-6,S-6);g.fillStyle='#755238';g.fillRect(px+8,py+8,S-16,8)}else if(t===2){g.fillStyle='#8d5e32';g.fillRect(px+6,py+6,S-12,S-12);g.strokeStyle='#c18d51';g.strokeRect(px+6,py+6,S-12,S-12);g.beginPath();g.moveTo(px+8,py+8);g.lineTo(px+S-8,py+S-8);g.moveTo(px+S-8,py+8);g.lineTo(px+8,py+S-8);g.stroke()}}for(const b of charges){const px=b.x*S+S/2,py=b.y*S+S/2;g.fillStyle='#45535d';g.beginPath();g.roundRect(px-14,py-14,28,28,6);g.fill();g.strokeStyle=b.t<.5?'#ffb34d':'#e8b95c';g.lineWidth=4;g.strokeRect(px-17,py-17,34,34)}for(const b of blasts){g.fillStyle='#ff9d36';g.globalAlpha=Math.min(1,b.t/.15);g.beginPath();g.arc(b.x*S+S/2,b.y*S+S/2,23,0,Math.PI*2);g.fill();g.globalAlpha=1}if(!(inv>0&&Math.floor(inv*12)%2))drawJohn(player.x,player.y);for(const e of enemies)if(!e.dead)drawEnemy(e);if(state!=='play'){g.fillStyle='#0b0806de';g.fillRect(0,0,c.width,c.height);g.textAlign='center';g.fillStyle='#e8b95c';g.font='800 18px system-ui';g.fillText('JOHN',c.width/2,c.height*.33);g.fillStyle='#f8f1e3';g.font='950 46px system-ui';g.fillText(state==='over'?'SHOP CLOSED':"JOHN'S SHOP BOMBER",c.width/2,c.height*.41);g.fillStyle='#e8b95c';g.font='700 20px system-ui';g.fillText(state==='over'?`Final score ${score}`:'Clear runaway shop junk with safe spark charges.',c.width/2,c.height*.48);g.fillStyle='#cbbdab';g.font='17px system-ui';g.fillText(state==='over'?msg:'Tap or press a direction to start',c.width/2,c.height*.54)}}
function loop(t){const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}makeRoom();requestAnimationFrame(loop)})();
''',extra_css='canvas{display:block;width:100%;aspect-ratio:13/15;background:#21170f;border:1px solid #6d5137;border-radius:18px;box-shadow:0 18px 58px #0009}.controls{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:10px;margin-top:8px}.dpad{display:grid;grid-template-columns:52px 52px 52px;grid-template-rows:44px 44px;gap:4px}.dpad button,.charge{border:1px solid #6a5035;background:#2a2018;color:#fff3da;border-radius:12px;font-weight:900;min-height:44px;touch-action:manipulation;font-size:9px}.dpad .up{grid-column:2}.dpad .left{grid-column:1;grid-row:2}.dpad .down{grid-column:2;grid-row:2}.dpad .right{grid-column:3;grid-row:2}.charge{justify-self:end;padding:0 14px;background:#9b4f31;font-size:10px}')

# 4 James Lumber Stack
base=(PUB/'cabin-blocks.html').read_text(encoding='utf-8')
base=base.replace('<title>Cabin Blocks</title>',"<title>James's Lumber Stack - Black Family Game Night</title>")
base=base.replace('<div class="brand">CABIN BLOCKS</div>',"<div class=\"brand\"><small>JAMES</small>JAMES'S LUMBER STACK</div>")
base=base.replace('Cabin falling blocks puzzle','James lumber stacking puzzle')
base=base.replace('Build clean rows from timber blocks','Quietly stack the yard before anyone moves it')
base=base.replace("state==='over'?'STACK TOPPED OUT':'CABIN BLOCKS'","state==='over'?\"COULDN'T FIT ANOTHER BOARD\":\"JAMES'S LUMBER STACK\"")
base=base.replace("localStorage.getItem('cabinBlocksBest')","localStorage.getItem('jamesLumberBest')")
base=base.replace("localStorage.setItem('cabinBlocksBest',best)","localStorage.setItem('jamesLumberBest',best)")
base=base.replace('const colors=[',"const BFGN_PROGRESS_KEY='bfgn_arcade_progress_v1',BFGN_ACH_KEY='bfgn_arcade_achievements_v1';function bfRead(k,f){try{return JSON.parse(localStorage.getItem(k)||'')||f}catch{return f}}function bfWrite(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}function bfPlay(id){const p=bfRead(BFGN_PROGRESS_KEY,{plays:0,games:{},wins:0});p.plays=(p.plays||0)+1;p.games=p.games||{};p.games[id]=(p.games[id]||0)+1;bfWrite(BFGN_PROGRESS_KEY,p)}function bfUnlock(id,label){const a=bfRead(BFGN_ACH_KEY,{});if(a[id])return;a[id]={label,at:Date.now()};bfWrite(BFGN_ACH_KEY,a);}\nconst colors=[")
base=base.replace("function reset(){board=", "function reset(){bfPlay('jamess-lumber-stack');board=")
base=base.replace("if(cleared){lines+=cleared;", "if(cleared){lines+=cleared;if(lines>=20)bfUnlock('james-level-organized','James-Level Organized');")
base=base.replace('<div class="foot"><span>Arrows / A-D', '<div class="foot"><span>James says: nice stack. Arrows / A-D')
base=base.replace('</style></head>', '.brand small{display:block;font-size:10px;color:#e8b95c;letter-spacing:.18em;margin-bottom:3px}</style></head>')
(PUB/'jamess-lumber-stack.html').write_text(base,encoding='utf-8')

# 5 Dorothy Garden Merge
base=(PUB/'camp-2048.html').read_text(encoding='utf-8')
base=base.replace('<title>Camp 2048</title>',"<title>Dorothy's Garden Merge - Black Family Game Night</title>")
base=base.replace('<div class="brand">CAMP 2048</div>',"<div class=\"brand\"><small>DOROTHY</small>DOROTHY'S GARDEN MERGE</div>")
base=base.replace('Camping merge puzzle','Dorothy garden merge puzzle')
base=base.replace("const names={2:['🔥','Match'],4:['🪵','Kindling'],8:['🪵','Log'],16:['🏮','Lantern'],32:['⛺','Tent'],64:['🧊','Cooler'],128:['🚐','Camper'],256:['🏕️','Campsite'],512:['🏠','Cabin'],1024:['🌲','Lodge'],2048:['🎉','Game Night']};", "const names={2:['SEED','Seed'],4:['SPRT','Sprout'],8:['FLWR','Flower'],16:['HERB','Herb Box'],32:['POT','Planter'],64:['ROW','Garden Row'],128:['TRLS','Trellis'],256:['GH','Greenhouse'],512:['GDN','Big Garden'],1024:['YARD','Backyard Oasis'],2048:['DOT','Dorothy Garden']};")
base=base.replace("localStorage.getItem('camp2048Best')","localStorage.getItem('dorothyGardenBest')")
base=base.replace("localStorage.setItem('camp2048Best',best)","localStorage.setItem('dorothyGardenBest',best)")
base=base.replace('NEW CAMP','NEW GARDEN')
base=base.replace('merge matching camp gear','merge matching garden pieces')
base=base.replace("CAMP 2048","DOROTHY'S GARDEN MERGE")
base=base.replace('</style></head>', '.brand small{display:block;font-size:10px;color:#e8b95c;letter-spacing:.18em;margin-bottom:3px}</style></head>')
base=base.replace("(()=>{const c=", "(()=>{const BFGN_PROGRESS_KEY='bfgn_arcade_progress_v1',BFGN_ACH_KEY='bfgn_arcade_achievements_v1';function bfRead(k,f){try{return JSON.parse(localStorage.getItem(k)||'')||f}catch{return f}}function bfWrite(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}function bfPlay(id){const p=bfRead(BFGN_PROGRESS_KEY,{plays:0,games:{},wins:0});p.plays=(p.plays||0)+1;p.games=p.games||{};p.games[id]=(p.games[id]||0)+1;bfWrite(BFGN_PROGRESS_KEY,p)}function bfUnlock(id,label){const a=bfRead(BFGN_ACH_KEY,{});if(a[id])return;a[id]={label,at:Date.now()};bfWrite(BFGN_ACH_KEY,a);}\nconst c=")
base=base.replace("function reset(){board=", "function reset(){bfPlay('dorothys-garden-merge');board=")
base=base.replace("score+=v;", "score+=v;if(v>=512)bfUnlock('dorothy-green-thumb','Dorothy Green Thumb');")
(PUB/'dorothys-garden-merge.html').write_text(base,encoding='utf-8')

# 6 Logan Minefield: rewrite compact
page('logans-minefield.html',"Logan's Minefield",'LOGAN',"LOGAN'S MINEFIELD",
     'SAFE <b id="safe">0</b> / FLAGS <b id="flags">0</b> / BEST <b id="best">--</b>',
     'width="600" height="600" aria-label="Logan outdoor hazard clearing puzzle"',
     '<div class="row"><button id="new">NEW PATH</button><span>Tap to clear. Hold or right-click to flag.</span></div>',
     'Avoid mud, hooks, rocks and the angry goose.',r'''
(()=>{const c=document.getElementById('game'),g=c.getContext('2d'),safeEl=document.getElementById('safe'),flagsEl=document.getElementById('flags'),bestEl=document.getElementById('best');const N=10,M=14,S=60;let board=[],state='ready',safe=0,flags=0,start=0,elapsed=0,pressTimer=0,longFired=false,msg='Logan knew this was a bad idea.';let best=Number(localStorage.getItem('loganMineBest')||0);bestEl.textContent=best?best+'s':'--';
function neighbors(i){const x=i%N,y=Math.floor(i/N),a=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)if(dx||dy){const nx=x+dx,ny=y+dy;if(nx>=0&&ny>=0&&nx<N&&ny<N)a.push(ny*N+nx)}return a}
function reset(){board=Array.from({length:N*N},()=>({mine:false,open:false,flag:false,n:0,kind:0}));const ids=[...Array(N*N).keys()];for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}for(const i of ids.slice(0,M)){board[i].mine=true;board[i].kind=Math.floor(Math.random()*4)}for(let i=0;i<N*N;i++)board[i].n=neighbors(i).filter(j=>board[j].mine).length;state='ready';safe=0;flags=0;elapsed=0;safeEl.textContent=0;flagsEl.textContent=0}
function open(i){if(state==='over'||state==='win')return;if(state==='ready'){state='play';start=performance.now();bfPlay('logans-minefield')}const z=board[i];if(!z||z.open||z.flag)return;if(z.mine){z.open=true;state='over';msg=['Logan knew this was a bad idea.','Should have gone fishing.','John is definitely yelling now.'][Math.floor(Math.random()*3)];return}z.open=true;safe++;safeEl.textContent=safe;if(z.n===0)for(const j of neighbors(i))if(!board[j].open&&!board[j].flag)open(j);if(safe===N*N-M){state='win';elapsed=Math.floor((performance.now()-start)/1000);if(!best||elapsed<best){best=elapsed;localStorage.setItem('loganMineBest',best);bestEl.textContent=best+'s'}bfUnlock('logan-safe-path','Logan Found a Safe Path');bfWin()}}
function flag(i){if(state==='over'||state==='win')return;if(state==='ready'){state='play';start=performance.now();bfPlay('logans-minefield')}const z=board[i];if(!z||z.open)return;z.flag=!z.flag;flags+=z.flag?1:-1;flagsEl.textContent=flags}
function hitIndex(e){const r=c.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)*N/r.width),y=Math.floor((e.clientY-r.top)*N/r.height);return y*N+x}
c.addEventListener('contextmenu',e=>{e.preventDefault();flag(hitIndex(e))});c.addEventListener('pointerdown',e=>{longFired=false;const i=hitIndex(e);pressTimer=setTimeout(()=>{longFired=true;flag(i)},480)});c.addEventListener('pointerup',e=>{clearTimeout(pressTimer);if(!longFired)open(hitIndex(e))});c.addEventListener('pointercancel',()=>clearTimeout(pressTimer));document.getElementById('new').addEventListener('click',reset);
function hazard(z,x,y){const labels=['MUD','HOOK','ROCK','GOOSE'];g.fillStyle=['#684934','#b89b4d','#77736a','#d9d5c8'][z.kind];g.beginPath();g.arc(x,y,19,0,Math.PI*2);g.fill();g.fillStyle='#1c1611';g.font='800 8px system-ui';g.textAlign='center';g.fillText(labels[z.kind],x,y+3)}
function draw(){if(state==='play')elapsed=Math.floor((performance.now()-start)/1000);g.fillStyle='#273c28';g.fillRect(0,0,600,600);for(let i=0;i<N*N;i++){const x=(i%N)*S,y=Math.floor(i/N)*S,z=board[i];g.fillStyle=z.open?'#bdad8a':'#4f6540';g.fillRect(x+2,y+2,S-4,S-4);g.strokeStyle='#293923';g.strokeRect(x+2,y+2,S-4,S-4);if(z.flag&&!z.open){g.fillStyle='#d7b45b';g.beginPath();g.moveTo(x+20,y+44);g.lineTo(x+20,y+14);g.lineTo(x+44,y+24);g.lineTo(x+20,y+31);g.fill()}if(z.open&&z.mine)hazard(z,x+30,y+30);else if(z.open&&z.n){g.fillStyle=['#5b6f9e','#588359','#ac7145','#a44b4b','#7e5d91','#9c774a','#555','#222'][z.n-1];g.font='950 24px system-ui';g.textAlign='center';g.fillText(z.n,x+30,y+39)}}g.fillStyle='#ffffffbb';g.font='700 12px system-ui';g.textAlign='left';g.fillText('TIME '+elapsed+'s',10,18);if(state==='ready'||state==='over'||state==='win'){g.fillStyle='#0b0a08df';g.fillRect(0,0,600,600);g.textAlign='center';g.fillStyle='#e8b95c';g.font='800 18px system-ui';g.fillText('LOGAN',300,190);g.fillStyle='#fff6e6';g.font='950 45px system-ui';g.fillText(state==='win'?'LOGAN MADE IT':state==='over'?"LOGAN'S DONE":"LOGAN'S MINEFIELD",300,250);g.fillStyle='#e8b95c';g.font='700 20px system-ui';g.fillText(state==='win'?`Safe in ${elapsed}s`:state==='over'?msg:'Clear a safe path without stepping in trouble.',300,305);g.fillStyle='#d0c1aa';g.font='17px system-ui';g.fillText(state==='ready'?'Tap a square to start':'Tap NEW PATH to play again',300,350)}}function loop(){draw();requestAnimationFrame(loop)}reset();loop()})();
''',extra_css='canvas{display:block;width:100%;aspect-ratio:1;background:#243725;border:1px solid #6b593d;border-radius:20px;box-shadow:0 18px 58px #0009;touch-action:none}.row{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-top:8px}.row button{min-height:44px;border:1px solid #6a5038;border-radius:11px;background:#2b2119;color:#f7ecd8;font-weight:900;padding:0 13px}.row span{font-size:11px;color:var(--muted)}')

# 7 Nana Goat Whack
base=(PUB/'goat-whack.html').read_text(encoding='utf-8')
base=base.replace('<title>Goat Whack</title>',"<title>Nana's Goat Whack - Black Family Game Night</title>")
base=base.replace('<div class="brand">GOAT WHACK</div>',"<div class=\"brand\"><small>NANA</small>NANA'S GOAT WHACK</div>")
base=base.replace('Goat Whack reaction game','Nana goat pen reaction game')
base=base.replace('Tap goats and pigs · avoid the red toolbox · 30 seconds','Tap goats, pigs and chickens. Avoid the red toolbox. 30 seconds.')
base=base.replace("r<.12?'tool':r<.36?'pig':'goat'","r<.12?'tool':r<.32?'pig':r<.48?'chicken':'goat'")
base=base.replace("const p=spots[t.i];if(!t.hit&&Math.hypot(x-p.x,y-p.y)<72){t.hit=true;hit=true;if(t.type==='tool'){score=Math.max(0,score-5);combo=0}else{combo++;score+=(t.type==='pig'?2:1)+Math.floor(combo/5);best=Math.max(best,score);localStorage.setItem('goatWhackBest',best)}sync();break}","const p=spots[t.i];if(!t.hit&&Math.hypot(x-p.x,y-p.y)<72){t.hit=true;hit=true;if(t.type==='tool'){score=Math.max(0,score-5);combo=0;nanaLine='Absolutely not.'}else{combo++;score+=(t.type==='pig'?2:t.type==='chicken'?2:1)+Math.floor(combo/5);nanaLine=['That is a sin.','Get out of there!','Papa!','Absolutely not.'][Math.floor(Math.random()*4)];best=Math.max(best,score);localStorage.setItem('nanaGoatWhackBest',best);if(score>=25)bfUnlock('thats-a-sin','That is a Sin')}sync();break}")
base=base.replace("localStorage.getItem('goatWhackBest')","localStorage.getItem('nanaGoatWhackBest')")
base=base.replace("localStorage.setItem('goatWhackBest',best)","localStorage.setItem('nanaGoatWhackBest',best)")
base=base.replace("let state='ready',score=0,combo=0,", "let nanaLine='That is a sin.',state='ready',score=0,combo=0,")
base=base.replace("function start(){state='play';", "function start(){bfPlay('nanas-goat-whack');nanaLine='Keep those animals under control.';state='play';")
base=base.replace("(()=>{const c=", "(()=>{const BFGN_PROGRESS_KEY='bfgn_arcade_progress_v1',BFGN_ACH_KEY='bfgn_arcade_achievements_v1';function bfRead(k,f){try{return JSON.parse(localStorage.getItem(k)||'')||f}catch{return f}}function bfWrite(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}function bfPlay(id){const p=bfRead(BFGN_PROGRESS_KEY,{plays:0,games:{},wins:0});p.plays=(p.plays||0)+1;p.games=p.games||{};p.games[id]=(p.games[id]||0)+1;bfWrite(BFGN_PROGRESS_KEY,p)}function bfUnlock(id,label){const a=bfRead(BFGN_ACH_KEY,{});if(a[id])return;a[id]={label,at:Date.now()};bfWrite(BFGN_ACH_KEY,a);}\nconst c=")
base=base.replace("if(t.type==='tool'){g.fillStyle='#b44435';", "if(t.type==='tool'){g.fillStyle='#b44435';")
base=base.replace("g.fillStyle=t.type==='pig'?'#dc9695':'#efe9da';", "g.fillStyle=t.type==='pig'?'#dc9695':t.type==='chicken'?'#e5c65b':'#efe9da';")
base=base.replace("if(t.type==='goat'){", "if(t.type==='goat'){")
base=base.replace("}else{g.fillStyle='#d27f82';g.beginPath();g.arc(0,15,17,0,Math.PI*2);g.fill()}", "}else if(t.type==='pig'){g.fillStyle='#d27f82';g.beginPath();g.arc(0,15,17,0,Math.PI*2);g.fill()}else{g.fillStyle='#c34835';g.beginPath();g.moveTo(0,-10);g.lineTo(8,-24);g.lineTo(14,-8);g.fill()}")
base=base.replace("g.fillText(`BEST ${best}`,18,28);", "g.fillText(`BEST ${best}`,18,28);g.textAlign='center';g.fillStyle='#f5e2b7';g.font='800 16px system-ui';g.fillText(nanaLine,300,34);")
base=base.replace("state==='over'?'TIME!':'GOAT WHACK'","state==='over'?\"THAT'S A SIN\":\"NANA'S GOAT WHACK\"")
base=base.replace('Fast hands in the goat pen','Nana is keeping this farm under control')
base=base.replace('</style></head>', '.brand small{display:block;font-size:10px;color:#e8b95c;letter-spacing:.18em;margin-bottom:3px}</style></head>')
(PUB/'nanas-goat-whack.html').write_text(base,encoding='utf-8')

# 8 Holly memory
page('hollys-memory-mayhem.html',"Holly's Memory Mayhem",'HOLLY',"HOLLY'S MEMORY MAYHEM",
     'MOVES <b id="moves">0</b> / TIME <b id="time">0</b> / BEST <b id="best">--</b>',
     'width="600" height="600" aria-label="Holly memory matching game"',
     '<div class="row"><div class="modes"><button data-mode="easy">EASY</button><button data-mode="medium" class="active">MEDIUM</button><button data-mode="hard">HARD</button></div><button id="new">RESHUFFLE</button></div>',
     'Match Holly favorites: squishies, dogs, hoodies and treats.',r'''
(()=>{const c=document.getElementById('game'),g=c.getContext('2d'),movesEl=document.getElementById('moves'),timeEl=document.getElementById('time'),bestEl=document.getElementById('best');const pool=[['SQ','Squishy','#d88db2'],['DOG','Dog','#9b765d'],['HOOD','Hoodie','#6b86ad'],['CAKE','Cupcake','#d89b78'],['STAR','Star Toy','#d7b64f'],['SHOE','Comfy Shoes','#8e76a8'],['HEART','Heart','#c95d68'],['BONE','Dog Bone','#d9c28e'],['BOW','Bow','#c784a9'],['POP','Pop Toy','#65a89c']];let mode='medium',cards=[],open=[],moves=0,matched=0,startAt=0,elapsed=0,state='ready',lock=false;let best=0;
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function cfg(){return mode==='easy'?{cols:4,rows:3,pairs:6}:mode==='hard'?{cols:5,rows:4,pairs:10}:{cols:4,rows:4,pairs:8}}
function bestKey(){return 'hollyMemoryBest_'+mode}
function reset(){best=Number(localStorage.getItem(bestKey())||0);bestEl.textContent=best||'--';const q=cfg(),chosen=pool.slice(0,q.pairs);cards=shuffle([...chosen,...chosen].map((p,i)=>({p,id:i,up:false,done:false})));open=[];moves=matched=0;elapsed=0;state='ready';lock=false;movesEl.textContent=0;timeEl.textContent=0}
function pick(i){if(lock)return;if(state==='ready'){state='play';startAt=performance.now();bfPlay('hollys-memory-mayhem')}if(state!=='play')return;const card=cards[i];if(!card||card.up||card.done)return;card.up=true;open.push(i);if(open.length===2){moves++;movesEl.textContent=moves;const [a,b]=open.map(k=>cards[k]);if(a.p[0]===b.p[0]){a.done=b.done=true;matched+=2;open=[];if(matched===cards.length){elapsed=Math.floor((performance.now()-startAt)/1000);state='win';if(!best||moves<best){best=moves;localStorage.setItem(bestKey(),best);bestEl.textContent=best}if(mode==='medium'&&moves<=14)bfUnlock('holly-memory-star','Holly Memory Star');bfWin()}}else{lock=true;setTimeout(()=>{a.up=b.up=false;open=[];lock=false},650)}}}
c.addEventListener('pointerdown',e=>{if(state==='win'){reset();return}const r=c.getBoundingClientRect(),x=(e.clientX-r.left)*600/r.width,y=(e.clientY-r.top)*600/r.height,q=cfg(),cw=600/q.cols,ch=600/q.rows,col=Math.floor(x/cw),row=Math.floor(y/ch);pick(row*q.cols+col)});document.getElementById('new').addEventListener('click',reset);document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));reset()}));
function draw(){if(state==='play'){elapsed=Math.floor((performance.now()-startAt)/1000);timeEl.textContent=elapsed}g.fillStyle='#2b1b24';g.fillRect(0,0,600,600);const q=cfg(),cw=600/q.cols,ch=600/q.rows;for(let i=0;i<cards.length;i++){const x=(i%q.cols)*cw,y=Math.floor(i/q.cols)*ch,z=cards[i];g.fillStyle=z.done?'#395d50':z.up?z.p[2]:'#4a2f42';g.beginPath();g.roundRect(x+7,y+7,cw-14,ch-14,15);g.fill();g.strokeStyle=z.up||z.done?'#f1d09b':'#7e5970';g.lineWidth=3;g.stroke();g.textAlign='center';if(z.up||z.done){g.fillStyle='#fff7e7';g.font=`950 ${Math.min(25,cw*.17)}px system-ui`;g.fillText(z.p[0],x+cw/2,y+ch*.48);g.fillStyle='#f0dcb8';g.font=`700 ${Math.min(13,cw*.09)}px system-ui`;g.fillText(z.p[1],x+cw/2,y+ch*.68)}else{g.fillStyle='#d9a8c0';g.font=`950 ${Math.min(34,cw*.22)}px Georgia`;g.fillText('H',x+cw/2,y+ch*.58)}}if(state==='ready'||state==='win'){g.fillStyle='#0a0709dc';g.fillRect(0,0,600,600);g.textAlign='center';g.fillStyle='#e8b95c';g.font='800 18px system-ui';g.fillText('HOLLY',300,188);g.fillStyle='#fff7e7';g.font='950 45px system-ui';g.fillText(state==='win'?'YAY! ALL MATCHED':"HOLLY'S MEMORY MAYHEM",300,250);g.fillStyle='#e8b95c';g.font='700 20px system-ui';g.fillText(state==='win'?`${moves} moves / ${elapsed}s`:'Find the matching cozy things.',300,305);g.fillStyle='#d0c2ac';g.font='17px system-ui';g.fillText(state==='win'?'Tap to reshuffle':'Tap a card to start',300,350)}}function loop(){draw();requestAnimationFrame(loop)}reset();loop()})();
''',extra_css='canvas{display:block;width:100%;aspect-ratio:1;background:#201712;border:1px solid #76576d;border-radius:20px;box-shadow:0 18px 58px #0009;touch-action:manipulation}.row{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-top:8px}.row button{min-height:42px;border:1px solid #76576d;border-radius:11px;background:#2f202a;color:#f7ecda;font-weight:850;padding:0 11px}.modes{display:flex;gap:5px}.modes button.active{background:#8b5f79;color:#fff}')

# 9 Lizzie Dramatic Lights
page('lizzies-dramatic-lights.html',"Lizzie's Dramatic Lights",'LIZZIE',"LIZZIE'S DRAMATIC LIGHTS",
     'ROUND <b id="round">0</b> / BEST <b id="best">0</b>',
     'width="600" height="600" aria-label="Lizzie dramatic sequence memory game"',
     '', 'Tap the stage pads in order. Keys 1-4 also work.',r'''
(()=>{const c=document.getElementById('game'),g=c.getContext('2d'),roundEl=document.getElementById('round'),bestEl=document.getElementById('best');const spots=[{x:180,y:210,col:'#d65470',freq:261.6,label:'SPIN'},{x:420,y:210,col:'#d9a047',freq:329.6,label:'POSE'},{x:180,y:430,col:'#6a78c7',freq:392,label:'TWIRL'},{x:420,y:430,col:'#9f6bc4',freq:523.3,label:'BOW'}];let seq=[],input=0,state='ready',active=-1,best=Number(localStorage.getItem('lizzieLightsBest')||0),audio=null,msg='Obviously, nail the sequence.';bestEl.textContent=best;
function ensureAudio(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()}function tone(i,d=.17){ensureAudio();const o=audio.createOscillator(),gain=audio.createGain();o.frequency.value=spots[i].freq;o.type='triangle';gain.gain.setValueAtTime(.001,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.13,audio.currentTime+.015);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(gain).connect(audio.destination);o.start();o.stop(audio.currentTime+d+.02)}function flash(i,ms=320){active=i;tone(i,ms/1000*.75);setTimeout(()=>{if(active===i)active=-1},ms)}function start(){seq=[];input=0;state='show';bfPlay('lizzies-dramatic-lights');nextRound()}function nextRound(){seq.push(Math.floor(Math.random()*4));roundEl.textContent=seq.length;input=0;state='show';msg=['Again!','Make it dramatic.','Do not ruin the entrance.','Obviously I nailed it.'][Math.floor(Math.random()*4)];let k=0;const delay=Math.max(350,650-seq.length*18);function step(){if(k>=seq.length){state='input';return}flash(seq[k++],Math.max(210,delay*.55));setTimeout(step,delay)}setTimeout(step,480)}function press(i){if(state==='ready'||state==='over'){start();return}if(state!=='input')return;flash(i,180);if(seq[input]!==i){state='over';best=Math.max(best,seq.length-1);localStorage.setItem('lizzieLightsBest',best);bestEl.textContent=best;msg='A tragic performance.';return}input++;if(input===seq.length){best=Math.max(best,seq.length);localStorage.setItem('lizzieLightsBest',best);bestEl.textContent=best;if(seq.length>=15)bfUnlock('drama-queen','Drama Queen');state='pause';setTimeout(nextRound,590)}}
c.addEventListener('pointerdown',e=>{const r=c.getBoundingClientRect(),x=(e.clientX-r.left)*600/r.width,y=(e.clientY-r.top)*600/r.height;if(state==='ready'||state==='over'){press(0);return}let bi=-1,dist=1e9;spots.forEach((s,i)=>{const d=Math.hypot(x-s.x,y-s.y);if(d<dist){dist=d;bi=i}});if(dist<98)press(bi)});addEventListener('keydown',e=>{const i=Number(e.key)-1;if(i>=0&&i<4){e.preventDefault();press(i)}if(e.code==='Space'&&(state==='ready'||state==='over')){e.preventDefault();press(0)}});
function draw(){g.fillStyle='#170d18';g.fillRect(0,0,600,600);const stage=g.createRadialGradient(300,300,20,300,300,330);stage.addColorStop(0,'#a33d7b20');stage.addColorStop(1,'#0000');g.fillStyle=stage;g.fillRect(0,0,600,600);g.fillStyle='#3b243c';g.fillRect(70,85,460,455);g.strokeStyle='#a36c9f';g.lineWidth=6;g.strokeRect(70,85,460,455);for(let i=0;i<spots.length;i++){const s=spots[i],on=active===i;g.save();g.shadowColor=s.col;g.shadowBlur=on?52:12;g.fillStyle=on?s.col:'#332d38';g.strokeStyle=on?'#fff0d0':s.col;g.lineWidth=5;g.beginPath();g.arc(s.x,s.y,82,0,Math.PI*2);g.fill();g.stroke();g.fillStyle=on?'#fff':'#d6c4d4';g.textAlign='center';g.font='950 20px system-ui';g.fillText(s.label,s.x,s.y+7);g.restore()}g.fillStyle='#d9a7bc';g.beginPath();g.arc(300,316,18,0,Math.PI*2);g.fill();g.strokeStyle='#d9a7bc';g.lineWidth=7;g.beginPath();g.moveTo(300,335);g.lineTo(300,380);g.moveTo(300,347);g.lineTo(270,365);g.moveTo(300,347);g.lineTo(330,365);g.moveTo(300,380);g.lineTo(278,416);g.moveTo(300,380);g.lineTo(322,416);g.stroke();if(state==='ready'||state==='over'){g.fillStyle='#090609df';g.fillRect(0,0,600,600);g.textAlign='center';g.fillStyle='#e8b95c';g.font='800 18px system-ui';g.fillText('LIZZIE',300,180);g.fillStyle='#fff6e8';g.font='950 43px system-ui';g.fillText(state==='over'?'A TRAGIC PERFORMANCE':"LIZZIE'S DRAMATIC LIGHTS",300,245);g.fillStyle='#e8b95c';g.font='700 20px system-ui';g.fillText(state==='over'?`Reached round ${Math.max(0,seq.length-1)}`:'Watch the stage. Copy every dramatic cue.',300,300);g.fillStyle='#d0c1cf';g.font='17px system-ui';g.fillText(state==='over'?msg:'Tap / Space to begin',300,345)}}function loop(){draw();requestAnimationFrame(loop)}loop()})();
''',extra_css='canvas{display:block;width:100%;aspect-ratio:1;background:#170d18;border:1px solid #76536f;border-radius:22px;box-shadow:0 18px 58px #0009;touch-action:manipulation}')

# 10 Vanessa Pipe Problem
page('vanessas-pipe-problem.html',"Vanessa's Pipe Problem",'VANESSA',"VANESSA'S PIPE PROBLEM",
     'JOB <b id="level">1</b> / MOVES <b id="moves">0</b> / TIME <b id="time">0</b>',
     'width="600" height="600" aria-label="Vanessa pipe rotation puzzle"',
     '<div class="row"><button id="new">NEW PROBLEM</button><span id="mission">Wash the GMC</span></div>',
     'Tap a pipe to rotate it. Vanessa is already eye-rolling.',r'''
(()=>{const c=document.getElementById('game'),g=c.getContext('2d'),levelEl=document.getElementById('level'),movesEl=document.getElementById('moves'),timeEl=document.getElementById('time'),missionEl=document.getElementById('mission');const N=6,S=100,NORTH=1,EAST=2,SOUTH=4,WEST=8,dirs=[[0,-1,NORTH,SOUTH],[1,0,EAST,WEST],[0,1,SOUTH,NORTH],[-1,0,WEST,EAST]],missions=['Wash the grey GMC','Fill the hot tub','Feed the campsite water line'];let target=[],tiles=[],level=1,moves=0,start=0,elapsed=0,state='play',lit=new Set(),completed=Number(localStorage.getItem('vanessaPipesCompleted')||0),comment='Seriously?';function idx(x,y){return y*N+x}function rot(mask){return ((mask<<1)&15)|((mask>>3)&1)}
function makeMaze(){target=Array(N*N).fill(0);const seen=new Set([0]),stack=[[0,0]];while(stack.length){const [x,y]=stack[stack.length-1],opts=[];for(const [dx,dy,a,b] of dirs){const nx=x+dx,ny=y+dy;if(nx>=0&&ny>=0&&nx<N&&ny<N&&!seen.has(idx(nx,ny)))opts.push([nx,ny,a,b])}if(!opts.length){stack.pop();continue}const [nx,ny,a,b]=opts[Math.floor(Math.random()*opts.length)];target[idx(x,y)]|=a;target[idx(nx,ny)]|=b;seen.add(idx(nx,ny));stack.push([nx,ny])}tiles=target.map(m=>{let r=m;const turns=Math.floor(Math.random()*4);for(let i=0;i<turns;i++)r=rot(r);return r});moves=0;elapsed=0;start=performance.now();state='play';movesEl.textContent=0;timeEl.textContent=0;missionEl.textContent=missions[(level-1)%missions.length];comment=['Seriously?','Who installed this?','John!','Unbelievable.'][Math.floor(Math.random()*4)];bfPlay('vanessas-pipe-problem');trace()}
function trace(){lit=new Set([0]);const q=[[0,0]];while(q.length){const [x,y]=q.shift(),m=tiles[idx(x,y)];for(const [dx,dy,a,b] of dirs)if(m&a){const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=N||ny>=N)continue;const ni=idx(nx,ny);if(!(tiles[ni]&b)||lit.has(ni))continue;lit.add(ni);q.push([nx,ny])}}if(lit.size===N*N&&state==='play'){state='win';elapsed=Math.floor((performance.now()-start)/1000);completed++;localStorage.setItem('vanessaPipesCompleted',completed);if(completed>=5)bfUnlock('eye-roll-expert','Eye Roll Expert');bfWin()}}
function turn(x,y){if(state==='win'){level++;levelEl.textContent=level;makeMaze();return}const i=idx(x,y);tiles[i]=rot(tiles[i]);moves++;movesEl.textContent=moves;trace()}c.addEventListener('pointerdown',e=>{const r=c.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)*N/r.width),y=Math.floor((e.clientY-r.top)*N/r.height);if(x>=0&&x<N&&y>=0&&y<N)turn(x,y)});document.getElementById('new').addEventListener('click',makeMaze);
function path(mask,cx,cy,on){g.lineCap='round';g.lineWidth=20;g.strokeStyle=on?'#63bfd1':'#8b806f';g.shadowColor=on?'#4bd8f5':'transparent';g.shadowBlur=on?20:0;g.beginPath();for(const [dx,dy,b] of [[0,-1,NORTH],[1,0,EAST],[0,1,SOUTH],[-1,0,WEST]])if(mask&b){g.moveTo(cx,cy);g.lineTo(cx+dx*43,cy+dy*43)}g.stroke();g.shadowBlur=0;g.fillStyle=on?'#dffbff':'#a89a85';g.beginPath();g.arc(cx,cy,13,0,Math.PI*2);g.fill()}
function draw(){if(state==='play'){elapsed=Math.floor((performance.now()-start)/1000);timeEl.textContent=elapsed}g.fillStyle='#211913';g.fillRect(0,0,600,600);for(let y=0;y<N;y++)for(let x=0;x<N;x++){const i=idx(x,y),px=x*S,py=y*S;g.fillStyle=(x+y)%2?'#3a2c22':'#33261e';g.fillRect(px+2,py+2,S-4,S-4);g.strokeStyle='#5a4433';g.strokeRect(px+2,py+2,S-4,S-4);path(tiles[i],px+50,py+50,lit.has(i));if(i===0){g.fillStyle='#4f8c5f';g.fillRect(px+10,py+10,24,18)}if(i===N*N-1){g.fillStyle='#7c7f83';g.beginPath();g.roundRect(px+57,py+62,30,17,5);g.fill();g.fillStyle='#222';g.beginPath();g.arc(px+63,py+80,5,0,Math.PI*2);g.arc(px+82,py+80,5,0,Math.PI*2);g.fill()}}g.fillStyle='#f1dfb7';g.font='800 15px system-ui';g.textAlign='center';g.fillText(comment,300,22);if(state==='win'){g.fillStyle='#0a0806df';g.fillRect(0,0,600,600);g.textAlign='center';g.fillStyle='#e8b95c';g.font='800 18px system-ui';g.fillText('VANESSA',300,190);g.fillStyle='#f8f1e2';g.font='950 42px system-ui';g.fillText('UNBELIEVABLE. IT WORKS.',300,252);g.fillStyle='#e8b95c';g.font='700 20px system-ui';g.fillText(`${moves} moves / ${elapsed}s`,300,305);g.fillStyle='#d0c1aa';g.font='17px system-ui';g.fillText('Tap any pipe for the next problem.',300,350)}}function loop(){draw();requestAnimationFrame(loop)}makeMaze();loop()})();
''',extra_css='canvas{display:block;width:100%;aspect-ratio:1;background:#201812;border:1px solid #6a5038;border-radius:20px;box-shadow:0 18px 58px #0009;touch-action:manipulation}.row{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-top:8px}.row button{min-height:44px;border:1px solid #6b523a;border-radius:11px;background:#2b2119;color:#f7ecd8;font-weight:850;padding:0 14px}.row span{font-size:12px;color:#d9c7a4;font-weight:800}')

# 11 Kelsi Rock Hunt
page('kelsis-rock-hunt.html',"Kelsi's Rock Hunt",'KELSI',"KELSI'S ROCK HUNT",
     'ROCKS <b id="score">0</b> / TIME <b id="time">45</b> / BEST <b id="best">0</b>',
     'width="600" height="720" aria-label="Kelsi rock hunt reaction game"',
     '', 'Tap shiny rocks. Prized rocks are worth 5.',r'''
(()=>{const c=document.getElementById('game'),g=c.getContext('2d'),scoreEl=document.getElementById('score'),timeEl=document.getElementById('time'),bestEl=document.getElementById('best');let state='ready',score=0,time=45,last=performance.now(),rocks=[],spawn=0,best=Number(localStorage.getItem('kelsiRockBest')||0),total=Number(localStorage.getItem('kelsiRocksTotal')||0);bestEl.textContent=best;function start(){state='play';score=0;time=45;rocks=[];spawn=0;bfPlay('kelsis-rock-hunt')}
function add(){const r=Math.random(),type=r<.12?'prize':r<.7?'shiny':'plain';rocks.push({x:45+Math.random()*510,y:90+Math.random()*555,r:20+Math.random()*12,type,life:2.5+Math.random()*2})}
c.addEventListener('pointerdown',e=>{if(state!=='play'){start();return}const r=c.getBoundingClientRect(),x=(e.clientX-r.left)*600/r.width,y=(e.clientY-r.top)*720/r.height;let hit=-1;for(let i=rocks.length-1;i>=0;i--)if(Math.hypot(x-rocks[i].x,y-rocks[i].y)<rocks[i].r+10){hit=i;break}if(hit>=0){const z=rocks.splice(hit,1)[0],pts=z.type==='prize'?5:z.type==='shiny'?2:1;score+=pts;total+=pts;localStorage.setItem('kelsiRocksTotal',total);scoreEl.textContent=score;best=Math.max(best,score);localStorage.setItem('kelsiRockBest',best);bestEl.textContent=best;if(total>=25)bfUnlock('rock-princess','Rock Princess')}});
function update(dt){if(state!=='play')return;time-=dt;timeEl.textContent=Math.ceil(Math.max(0,time));spawn-=dt;if(spawn<=0){spawn=.42+Math.random()*.4;add()}for(const r of rocks)r.life-=dt;rocks=rocks.filter(r=>r.life>0);if(time<=0){time=0;state='over'}}
function drawDog(){g.fillStyle='#eee6d4';g.beginPath();g.ellipse(300,665,58,31,0,0,Math.PI*2);g.fill();g.beginPath();g.arc(335,638,27,0,Math.PI*2);g.fill();g.fillStyle='#d9b65b';g.beginPath();g.moveTo(323,616);g.lineTo(333,596);g.lineTo(342,617);g.fill();g.fillStyle='#222';g.beginPath();g.arc(343,636,3,0,Math.PI*2);g.fill();g.fillStyle='#d79ab1';g.fillRect(355,650,9,19)}
function draw(){g.fillStyle='#35452c';g.fillRect(0,0,600,720);for(let i=0;i<70;i++){const x=(i*83)%600,y=50+((i*137)%570);g.fillStyle=i%3?'#6a6658':'#777162';g.beginPath();g.ellipse(x,y,13+(i%7),9+(i%4),.2,0,Math.PI*2);g.fill()}for(const r of rocks){g.save();if(r.type!=='plain'){g.shadowColor=r.type==='prize'?'#ffd76a':'#a7e8ff';g.shadowBlur=r.type==='prize'?28:16}g.fillStyle=r.type==='prize'?'#d6a73e':r.type==='shiny'?'#9ab8c0':'#746e61';g.beginPath();g.ellipse(r.x,r.y,r.r,r.r*.72,.25,0,Math.PI*2);g.fill();if(r.type==='prize'){g.fillStyle='#fff4b8';g.beginPath();g.arc(r.x-7,r.y-6,5,0,Math.PI*2);g.fill()}g.restore()}drawDog();if(state!=='play'){g.fillStyle='#090806dd';g.fillRect(0,0,600,720);g.textAlign='center';g.fillStyle='#e8b95c';g.font='800 18px system-ui';g.fillText('KELSI',300,250);g.fillStyle='#fff6e6';g.font='950 48px system-ui';g.fillText(state==='over'?'ROCK PRINCESS':"KELSI'S ROCK HUNT",300,315);g.fillStyle='#e8b95c';g.font='700 21px system-ui';g.fillText(state==='over'?`Found ${score} points of rocks`:'Find the best rocks before time runs out.',300,365);g.fillStyle='#d0c1aa';g.font='17px system-ui';g.fillText(state==='over'?'Tap to hunt again':'Tap to start',300,410)}}function loop(t){const dt=Math.min(.05,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop)})();
''',extra_css='canvas{display:block;width:100%;aspect-ratio:5/6;background:#35452c;border:1px solid #6a5c3e;border-radius:20px;box-shadow:0 18px 58px #0009;touch-action:manipulation}')

# 12 Molly Light Chase
page('mollys-light-chase.html',"Molly's Light Chase",'MOLLY',"MOLLY'S LIGHT CHASE",
     'CAUGHT <b id="score">0</b> / TIME <b id="time">30</b> / BEST <b id="best">0</b>',
     'width="600" height="720" aria-label="Molly light chase reaction game"',
     '', 'Tap the moving light before Molly loses it.',r'''
(()=>{const c=document.getElementById('game'),g=c.getContext('2d'),scoreEl=document.getElementById('score'),timeEl=document.getElementById('time'),bestEl=document.getElementById('best');let state='ready',score=0,time=30,last=performance.now(),best=Number(localStorage.getItem('mollyLightBest')||0),dog={x:300,y:620},orb={x:300,y:260,vx:190,vy:155,r:24},burst=0;bestEl.textContent=best;function resetOrb(){orb.x=80+Math.random()*440;orb.y=90+Math.random()*430;const a=Math.random()*Math.PI*2,s=180+Math.random()*120;orb.vx=Math.cos(a)*s;orb.vy=Math.sin(a)*s}function start(){state='play';score=0;time=30;scoreEl.textContent=0;bfPlay('mollys-light-chase');resetOrb()}
c.addEventListener('pointerdown',e=>{if(state!=='play'){start();return}const r=c.getBoundingClientRect(),x=(e.clientX-r.left)*600/r.width,y=(e.clientY-r.top)*720/r.height;if(Math.hypot(x-orb.x,y-orb.y)<orb.r+24){score++;scoreEl.textContent=score;dog.x=orb.x;dog.y=Math.min(620,orb.y+70);burst=.25;best=Math.max(best,score);localStorage.setItem('mollyLightBest',best);bestEl.textContent=best;if(score>=30)bfUnlock('molly-loves-lights','Molly Loves Lights');resetOrb()}});
function update(dt){if(state!=='play')return;time-=dt;timeEl.textContent=Math.ceil(Math.max(0,time));orb.x+=orb.vx*dt;orb.y+=orb.vy*dt;if(orb.x<45&&orb.vx<0||orb.x>555&&orb.vx>0)orb.vx*=-1;if(orb.y<60&&orb.vy<0||orb.y>520&&orb.vy>0)orb.vy*=-1;burst=Math.max(0,burst-dt);if(time<=0)state='over'}
function drawMolly(){g.save();g.translate(dog.x,dog.y);g.fillStyle='#caa27d';g.beginPath();g.ellipse(0,5,43,27,0,0,Math.PI*2);g.fill();g.beginPath();g.arc(28,-18,25,0,Math.PI*2);g.fill();g.fillStyle='#6d4c35';g.beginPath();g.ellipse(14,-35,12,24,-.5,0,Math.PI*2);g.fill();g.fillStyle='#222';g.beginPath();g.arc(36,-23,3,0,Math.PI*2);g.fill();g.fillStyle='#e58d9a';g.beginPath();g.roundRect(38,-6,10,25,5);g.fill();g.restore()}
function draw(){g.fillStyle='#151527';g.fillRect(0,0,600,720);for(let i=0;i<55;i++){g.fillStyle=`rgba(255,255,255,${.05+(i%5)*.02})`;g.fillRect((i*97)%600,(i*53)%560,2,2)}g.save();g.shadowColor='#fff36a';g.shadowBlur=burst?55:35;g.fillStyle='#fff36a';g.beginPath();g.arc(orb.x,orb.y,orb.r+(burst?8:0),0,Math.PI*2);g.fill();g.fillStyle='#fff';g.beginPath();g.arc(orb.x-7,orb.y-8,6,0,Math.PI*2);g.fill();g.restore();drawMolly();if(state!=='play'){g.fillStyle='#080811df';g.fillRect(0,0,600,720);g.textAlign='center';g.fillStyle='#e8b95c';g.font='800 18px system-ui';g.fillText('MOLLY',300,250);g.fillStyle='#fff6e6';g.font='950 47px system-ui';g.fillText(state==='over'?'TONGUE OUT, LIGHT GONE':"MOLLY'S LIGHT CHASE",300,315);g.fillStyle='#e8b95c';g.font='700 21px system-ui';g.fillText(state==='over'?`Caught ${score} lights`:'Molly loves lights. Catch as many as you can.',300,365);g.fillStyle='#d0c1aa';g.font='17px system-ui';g.fillText(state==='over'?'Tap to chase again':'Tap to start',300,410)}}function loop(t){const dt=Math.min(.05,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop)})();
''',extra_css='canvas{display:block;width:100%;aspect-ratio:5/6;background:#151527;border:1px solid #5d5877;border-radius:20px;box-shadow:0 18px 58px #0009;touch-action:manipulation}')

# 13 Gunner Snack Attack
page('gunners-snack-attack.html',"Gunner's Snack Attack",'GUNNER BONUS',"GUNNER'S SNACK ATTACK",
     'SNACKS <b id="score">0</b> / TIME <b id="time">45</b> / BEST <b id="best">0</b>',
     'width="600" height="720" aria-label="Gunner snack collection game"',
     '<div class="dpad"><button data-d="0,-1">UP</button><button data-d="-1,0">LEFT</button><button data-d="0,1">DOWN</button><button data-d="1,0">RIGHT</button></div>',
     'Arrows / WASD / swipe. Snacks good. Chores bad.',r'''
(()=>{const c=document.getElementById('game'),g=c.getContext('2d'),scoreEl=document.getElementById('score'),timeEl=document.getElementById('time'),bestEl=document.getElementById('best');const COL=8,ROW=9,S=70,OX=20,OY=45;let state='ready',score=0,time=45,last=performance.now(),best=Number(localStorage.getItem('gunnerSnackBest')||0),moveCooldown=0;const dog={x:3,y:7};let snack={x:2,y:2},chores=[];bestEl.textContent=best;function freeCell(){let x,y;do{x=Math.floor(Math.random()*COL);y=Math.floor(Math.random()*ROW)}while((x===dog.x&&y===dog.y)||chores.some(q=>q.x===x&&q.y===y));return{x,y}}function resetObjects(){snack=freeCell();chores=[];for(let i=0;i<6;i++){const q=freeCell();chores.push(q)}}function start(){state='play';score=0;time=45;dog.x=3;dog.y=7;scoreEl.textContent=0;bfPlay('gunners-snack-attack');resetObjects()}
function move(dx,dy){if(state!=='play'){start();return}if(moveCooldown>0)return;moveCooldown=.07;dog.x=Math.max(0,Math.min(COL-1,dog.x+dx));dog.y=Math.max(0,Math.min(ROW-1,dog.y+dy));if(dog.x===snack.x&&dog.y===snack.y){score++;scoreEl.textContent=score;best=Math.max(best,score);localStorage.setItem('gunnerSnackBest',best);bestEl.textContent=best;if(score>=20)bfUnlock('gunner-snack-attack','Snack Attack');snack=freeCell()}if(chores.some(q=>q.x===dog.x&&q.y===dog.y)){score=Math.max(0,score-1);scoreEl.textContent=score;dog.x=3;dog.y=7}}
addEventListener('keydown',e=>{const d={ArrowLeft:[-1,0],a:[-1,0],A:[-1,0],ArrowRight:[1,0],d:[1,0],D:[1,0],ArrowUp:[0,-1],w:[0,-1],W:[0,-1],ArrowDown:[0,1],s:[0,1],S:[0,1]}[e.key];if(d){e.preventDefault();move(...d)}});document.querySelectorAll('[data-d]').forEach(b=>b.addEventListener('pointerdown',()=>move(...b.dataset.d.split(',').map(Number))));let sx=0,sy=0;c.addEventListener('pointerdown',e=>{if(state!=='play'){start();return}sx=e.clientX;sy=e.clientY});c.addEventListener('pointerup',e=>{if(state!=='play')return;const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<18)return;Math.abs(dx)>Math.abs(dy)?move(Math.sign(dx),0):move(0,Math.sign(dy))});
function update(dt){moveCooldown=Math.max(0,moveCooldown-dt);if(state!=='play')return;time-=dt;timeEl.textContent=Math.ceil(Math.max(0,time));if(time<=0)state='over'}
function drawDog(){const x=OX+dog.x*S+S/2,y=OY+dog.y*S+S/2;g.fillStyle='#6a4c37';g.beginPath();g.ellipse(x,y+4,28,20,0,0,Math.PI*2);g.fill();g.beginPath();g.arc(x+6,y-18,19,0,Math.PI*2);g.fill();g.fillStyle='#e58d9a';g.fillRect(x+18,y-8,8,18)}
function draw(){g.fillStyle='#2d3f2a';g.fillRect(0,0,600,720);for(let y=0;y<ROW;y++)for(let x=0;x<COL;x++){g.fillStyle=(x+y)%2?'#42563b':'#394d34';g.fillRect(OX+x*S,OY+y*S,S-3,S-3)}for(const q of chores){const x=OX+q.x*S+S/2,y=OY+q.y*S+S/2;g.strokeStyle='#bf8b53';g.lineWidth=5;g.beginPath();g.moveTo(x-16,y+20);g.lineTo(x+16,y-20);g.stroke();g.fillStyle='#9e4c3f';g.fillRect(x-22,y+14,25,9)}{const x=OX+snack.x*S+S/2,y=OY+snack.y*S+S/2;g.fillStyle='#d9bc78';g.beginPath();g.arc(x-9,y,9,0,Math.PI*2);g.arc(x+9,y,9,0,Math.PI*2);g.fill();g.fillRect(x-9,y-5,18,10)}drawDog();if(state!=='play'){g.fillStyle='#090806df';g.fillRect(0,0,600,720);g.textAlign='center';g.fillStyle='#e8b95c';g.font='800 18px system-ui';g.fillText('GUNNER BONUS',300,250);g.fillStyle='#fff6e6';g.font='950 46px system-ui';g.fillText(state==='over'?'WORK AVOIDED':"GUNNER'S SNACK ATTACK",300,315);g.fillStyle='#e8b95c';g.font='700 21px system-ui';g.fillText(state==='over'?`Snacks collected: ${score}`:'Collect snacks while avoiding actual work.',300,365);g.fillStyle='#d0c1aa';g.font='17px system-ui';g.fillText(state==='over'?'Tap to snack again':'Tap or press a direction to start',300,410)}}function loop(t){const dt=Math.min(.05,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}resetObjects();requestAnimationFrame(loop)})();
''',extra_css='canvas{display:block;width:100%;aspect-ratio:5/6;background:#2d3f2a;border:1px solid #6b593d;border-radius:20px;box-shadow:0 18px 58px #0009;touch-action:none}.dpad{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:8px}.dpad button{min-height:44px;border:1px solid #6a5038;border-radius:11px;background:#2b2119;color:#f7ecd8;font-weight:900;font-size:10px}')

# Cleanup old generic Phase U2 files replaced by personalized versions
for f in ['camp-pong.html','goat-crossing.html','shop-bomber.html','cabin-blocks.html','camp-2048.html','minefield.html','goat-whack.html','memory-mayhem.html','firelight-simon.html','papas-pipes.html']:
    p=PUB/f
    if p.exists(): p.unlink()

print('Generated Phase U3 family arcade files')
