from pathlib import Path
import json,re
root=Path('/mnt/data/w24_earrings_build')
p=root/'public/avatar-cosmetics.mjs'
s=p.read_text()
m=re.search(r'export const COSMETIC_CATALOG=(\[.*?\]);\nexport const COSMETIC_BY_ID=',s,re.S)
if not m: raise SystemExit('catalog not found')
cat=json.loads(m.group(1))
ids={x['id'] for x in cat}
items=[
 dict(id='w24-e01-small-studs',slot='earrings',name='Small Stud Earrings',price=120,asset='/cosmetics/w24-flagship-earrings/e01-small-studs.png',shopAsset='/cosmetics/w24-flagship-earrings/shop-e01-small-studs.png',category='Jewelry',collection='W24 Flagship Earrings',rarity='Premium',source='token',desc='Polished silver studs with real 3D form, soft highlights, and clean low-profile fit.',role='Hero',fitMode='semantic-earlobes',fitAnchor='earlobes',dogAdaptation='Ear charm fit',giftable=True,animated=False,visualConcept='Small polished studs; classic, subtle, premium 3D shop standard.',productionNotes='Approved W24 art direction. Use semantic earlobe anchors. Store uses single-ear hero render; equipped overlay uses matched pair.',catalogVersion=24,legacyPreserved=False,artStatus='Approved Art',reviewStatus='Approve Concept',approvedForLive=False,variantStrategy='finish-options',stage1Technical='Pending Integration QA',stage2Visual='Actual Avatar Fit Pending',fitAuditStatus='Pending Actual Avatar Matrix',visualRuntimeStatus='Production Art Integrated'),
 dict(id='w24-e02-medium-hoops',slot='earrings',name='Medium Hoop Earrings',price=160,asset='/cosmetics/w24-flagship-earrings/e02-medium-hoops.png',shopAsset='/cosmetics/w24-flagship-earrings/shop-e02-medium-hoops.png',category='Jewelry',collection='W24 Flagship Earrings',rarity='Premium',source='token',desc='Polished gold hoops with dimensional tube geometry and a clean everyday silhouette.',role='Hero',fitMode='semantic-earlobes',fitAnchor='earlobes',dogAdaptation='Ear charm fit',giftable=True,animated=False,visualConcept='Medium polished gold hoops; stylish everyday premium 3D cosmetic.',productionNotes='Approved W24 art direction. Use semantic earlobe anchors. Store uses single-ear hero render; equipped overlay uses matched pair.',catalogVersion=24,legacyPreserved=False,artStatus='Approved Art',reviewStatus='Approve Concept',approvedForLive=False,variantStrategy='finish-options',stage1Technical='Pending Integration QA',stage2Visual='Actual Avatar Fit Pending',fitAuditStatus='Pending Actual Avatar Matrix',visualRuntimeStatus='Production Art Integrated'),
 dict(id='w24-e03-pearl-drops',slot='earrings',name='Pearl Drop Earrings',price=190,asset='/cosmetics/w24-flagship-earrings/e03-pearl-drops.png',shopAsset='/cosmetics/w24-flagship-earrings/shop-e03-pearl-drops.png',category='Jewelry',collection='W24 Flagship Earrings',rarity='Premium',source='token',desc='Soft pearl drops with gold hardware, dimensional shading, and a refined hanging profile.',role='Hero',fitMode='semantic-earlobes',fitAnchor='earlobes',dogAdaptation='Ear charm fit',giftable=True,animated=False,visualConcept='Pearl and metal drops; timeless, refined, premium 3D cosmetic.',productionNotes='Approved W24 art direction. Use semantic earlobe anchors. Store uses single-ear hero render; equipped overlay uses matched pair.',catalogVersion=24,legacyPreserved=False,artStatus='Approved Art',reviewStatus='Approve Concept',approvedForLive=False,variantStrategy='finish-options',stage1Technical='Pending Integration QA',stage2Visual='Actual Avatar Fit Pending',fitAuditStatus='Pending Actual Avatar Matrix',visualRuntimeStatus='Production Art Integrated'),
 dict(id='w24-e04-gem-dangles',slot='earrings',name='Gem Dangle Earrings',price=220,asset='/cosmetics/w24-flagship-earrings/e04-gem-dangles.png',shopAsset='/cosmetics/w24-flagship-earrings/shop-e04-gem-dangles.png',category='Jewelry',collection='W24 Flagship Earrings',rarity='Premium',source='token',desc='Emerald-tone gem dangles with gold edging and a bold, dimensional dressy finish.',role='Hero',fitMode='semantic-earlobes',fitAnchor='earlobes',dogAdaptation='Ear charm fit',giftable=True,animated=False,visualConcept='Faceted emerald-tone gem with polished gold hardware; elegant movement profile.',productionNotes='Approved W24 art direction. Use semantic earlobe anchors. Store uses single-ear hero render; equipped overlay uses matched pair.',catalogVersion=24,legacyPreserved=False,artStatus='Approved Art',reviewStatus='Approve Concept',approvedForLive=False,variantStrategy='finish-options',stage1Technical='Pending Integration QA',stage2Visual='Actual Avatar Fit Pending',fitAuditStatus='Pending Actual Avatar Matrix',visualRuntimeStatus='Production Art Integrated'),
 dict(id='w24-e05-heart-charms',slot='earrings',name='Heart Charm Earrings',price=170,asset='/cosmetics/w24-flagship-earrings/e05-heart-charms.png',shopAsset='/cosmetics/w24-flagship-earrings/shop-e05-heart-charms.png',category='Jewelry',collection='W24 Flagship Earrings',rarity='Premium',source='token',desc='Pink heart charms with gold trim, dimensional enamel-style surfaces, and a playful premium finish.',role='Hero',fitMode='semantic-earlobes',fitAnchor='earlobes',dogAdaptation='Ear charm fit',giftable=True,animated=False,visualConcept='Tasteful pink heart charm drops; playful, sweet, premium 3D cosmetic.',productionNotes='Approved W24 art direction. Use semantic earlobe anchors. Store uses single-ear hero render; equipped overlay uses matched pair.',catalogVersion=24,legacyPreserved=False,artStatus='Approved Art',reviewStatus='Approve Concept',approvedForLive=False,variantStrategy='finish-options',stage1Technical='Pending Integration QA',stage2Visual='Actual Avatar Fit Pending',fitAuditStatus='Pending Actual Avatar Matrix',visualRuntimeStatus='Production Art Integrated'),
 dict(id='w24-e06-statement-earrings',slot='earrings',name='Statement Fashion Earrings',price=260,asset='/cosmetics/w24-flagship-earrings/e06-statement-earrings.png',shopAsset='/cosmetics/w24-flagship-earrings/shop-e06-statement-earrings.png',category='Jewelry',collection='W24 Flagship Earrings',rarity='Legendary',source='token',desc='Bold gold diamond-frame earrings with dark resin insets and a strong fashion-forward silhouette.',role='Hero',fitMode='semantic-earlobes',fitAnchor='earlobes',dogAdaptation='Ear charm fit',giftable=True,animated=False,visualConcept='Large statement earring with gold frame and dark resin center; bold premium silhouette.',productionNotes='Approved W24 art direction. Use semantic earlobe anchors. Store uses single-ear hero render; equipped overlay uses matched pair.',catalogVersion=24,legacyPreserved=False,artStatus='Approved Art',reviewStatus='Approve Concept',approvedForLive=False,variantStrategy='finish-options',stage1Technical='Pending Integration QA',stage2Visual='Actual Avatar Fit Pending',fitAuditStatus='Pending Actual Avatar Matrix',visualRuntimeStatus='Production Art Integrated')
]
cat=[x for x in cat if x.get('id') not in {i['id'] for i in items}]
cat=items+cat
new='export const COSMETIC_CATALOG='+json.dumps(cat,separators=(',',':'))+';\nexport const COSMETIC_BY_ID='
s=s[:m.start()]+new+s[m.end():]
# Add earlobe-specific semantic fitting before generic earrings.
old="else if(slot==='filter'){const a=anchor(avatar,'head');f={x:a.x,y:a.y+30,w:a.w*1.34}}\n else if(slot==='earrings'){const a=anchor(avatar,'ears');f={x:a.x,y:a.y+15,w:a.w*1.18}}"
newfit="else if(slot==='filter'){const a=anchor(avatar,'head');f={x:a.x,y:a.y+30,w:a.w*1.34}}\n else if(slot==='earrings'&&semantic==='earlobes'){const a=anchor(avatar,'ears'),h=anchor(avatar,'head');f={x:a.x,y:a.y+(dog?7:5),w:a.w*(dog?1.16:1.14),r:(Number.isFinite(h.r)?h.r:0)*.35}}\n else if(slot==='earrings'){const a=anchor(avatar,'ears');f={x:a.x,y:a.y+15,w:a.w*1.18}}"
if old not in s: raise SystemExit('fit insertion target not found')
s=s.replace(old,newfit)
p.write_text(s)

# Store cards use the dedicated hero thumbnail when one exists.
store=root/'public/tokens-store.html'
t=store.read_text()
t=t.replace('<img loading="lazy" src="${x.asset}" alt="${esc(x.name)}">','<img loading="lazy" src="${x.raw?.shopAsset||x.asset}" alt="${esc(x.name)}">')
store.write_text(t)

# Version/cache bump and pre-cache the W24 assets.
sw=root/'public/sw.js'; w=sw.read_text()
w=w.replace("const PHASE_W22_CACHE='black-family-game-night-staging-phase-w23-cabin-regression-recovery-48';\nconst CACHE=PHASE_W22_CACHE;","const PHASE_W22_CACHE='black-family-game-night-staging-phase-w23-cabin-regression-recovery-48';\nconst PHASE_W24_CACHE='black-family-game-night-staging-phase-w24-flagship-earrings-49';\nconst CACHE=PHASE_W24_CACHE;")
needle="'/icon-512.png'];"
assets=[f"'/cosmetics/w24-flagship-earrings/{n}.png'" for n in ['e01-small-studs','e02-medium-hoops','e03-pearl-drops','e04-gem-dangles','e05-heart-charms','e06-statement-earrings','shop-e01-small-studs','shop-e02-medium-hoops','shop-e03-pearl-drops','shop-e04-gem-dangles','shop-e05-heart-charms','shop-e06-statement-earrings']]
w=w.replace(needle,"'/icon-512.png',"+','.join(assets)+'];')
sw.write_text(w)

pkg=root/'package.json'; d=json.load(open(pkg)); d['version']='3.22.0-staging-phase-w24-flagship-earrings-49'; d['description']='Black Family Game Night W24: first production-quality 3D flagship earrings integrated into the shop with semantic earlobe fitting while preserving the Build 48 cabin recovery.'; pkg.write_text(json.dumps(d,indent=2)+"\n")
print('Integrated',len(items),'W24 earrings; catalog size',len(cat))
